NON_KEY_DESC = 'non-gestalt-key'

unknown_keys_desc = {
    "/4LCTfMhvzuiK6b557ir5Q": f"{NON_KEY_DESC}, IODeviceTree:/arm-io/isp, starts with o, LiDARCalibrationPrCL",
    "1HWDBfJwBJZ8TDHcPDafmQ": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with e, DeviceHasEmbeddedSIMOnlyBoard",
    "3Hj0jFscGt094g65Fag7eQ": f"{NON_KEY_DESC}, Hardware platform, starts with t",
    "8Kc1MRjWTfDiGKX6E/9XqQ": f"{NON_KEY_DESC}, IODeviceTree:/product/audio, starts with l, DeviceSupportsLongFormAudio",
    "8kcKPCGGyCpf66MMl5TVkA": f"{NON_KEY_DESC}, IODeviceTree:/multi-touch, starts with m, MultiTouchMaxBootTime",
    "9f5ODNAt2gufqSI82eYnLw": f"{NON_KEY_DESC}, IODeviceTree:/multi-touch, starts with c, DeviceSupportsCorrectedTemperature",
    "bbyFCcrPE+k6ZXIVbXSFUw": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with u, DevicePrefersBuildingStrokes",
    "bxQyyA/qJ3QQXTiHBsW2eg": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with o, BuddyLanguagesAnimationRequiresOptimization",
    "cq/jTAQ8zJab+ibcGUzJew": f"{NON_KEY_DESC}, IODeviceTree:/product/audio, starts with m, DeviceSupportsBeacon",
    "CUMH6bG4DFnu7ZREp5YkUQ": f"{NON_KEY_DESC}, IODeviceTree:/product/camera, starts with j, RearFacingCameraTimeOfFlightCameraCapability",
    "D3LeXyjrxDFYSi6pWFEL4A": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with u, DeviceSupportsTrafficAlpha",
    "dUipfYkyvM80t4IkmMBVgQ": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with w, DeviceSupportsElton",
    "dW6ROVcD3o5ACa4jvALJ6A": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with d, DynamicFunctionRowSerialNumber",
    "e+pTfaabi1k1kfdk2vl1Kw": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with l, LunaFlexSerialNumber",
    "E3qwwdwgUSy6FV6VC+Uf3A": f"{NON_KEY_DESC}, IODeviceTree:/chosen, starts with r, ResearchFuse",
    "flgGiGu1dR1hEWcC1cTLTw": f"{NON_KEY_DESC}, IODeviceTree:/product/camera, starts with r, RearFacingLowLightCameraCapability",
    "GvmsjQ/68T7do2CJxUhMig": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with b, RemoteBluetoothAddressData",
    "H4f1y1sEDUUUROeb4FZJ4A": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with n, RequiresNaturalVolumeButtonArrangement",
    "HhLXszMhK6bb9TP4sqVQWQ": f"{NON_KEY_DESC}, IODeviceTree:/chosen, starts with e, ExtendedSecurityDomain",
    "ieuwDGiHrHoYRjSl6gT+1A": f"{NON_KEY_DESC}, IODeviceTree:/product/audio, starts with s, DeviceSupportsConcurrentHPLPMics",
    "is3zjHrEdiF6J/boqghy9A": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with m, PintoMacAddressData",
    "j/8nlHWXO3OvKHQHgl905Q": f"{NON_KEY_DESC}, IODeviceTree:/product/camera, starts with f, FrontCameraRotationForISP",
    "JljZ8PqQJB8QlFC2NsgOPw": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with e, WorkoutUltraMode",
    "KWr9OM2iqeLQEhaHS0UshQ": f"{NON_KEY_DESC}, IODeviceTree:/arm-io/i2c0/audio0, starts with a, DeviceSupportsLineIn",
    "ldJQht23DQY8SUXKJhUvPw": f"{NON_KEY_DESC}, IODeviceTree:/backlight, starts with u, DeviceSupportsFrameSynchronousBrightness",
    "lFFadhW8h/hfpcu601hyqg": f"{NON_KEY_DESC}, IODeviceTree:/, starts with h, DeviceSupportsInductiveCharging",
    "lR7sjp4tOz3cMWoEMlZrLA": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with u, DevicePrefers3DBuildingStrokes",
    "M2qC9+75568xA1E3I+r+dg": f"{NON_KEY_DESC}, IODeviceTree:/, starts with s",
    "mug/QuG6jZ3CYR9p7OWQaw": f"{NON_KEY_DESC}, IODeviceTree:/opal, starts with b",
    "oOV1jhJbdV3AddkcCg0AEA": "MetalPerfLevelCapabilityOne4IOS (mismatched)",
    "P1djMN/L3B6otgGpO9WYkw": f"{NON_KEY_DESC}, IODeviceTree:/, starts with s, SiliconBringupBoard",
    "qAAQUPLjf+Hl4UM3WY2qgw": f"{NON_KEY_DESC}, IODeviceTree:/product/camera, starts with f, FrontFacingCameraHFRVideoCapture720pMaxFPS",
    "QY61T8CLLwG/yu92ScTYtw": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with s, driverkit",
    "rt/G6Vk3NTGWs5N9WEjztQ": f"{NON_KEY_DESC}, IODeviceTree:/product/camera, starts with f, FrontFacingLowLightCameraCapability",
    "sad18VQX7AeS+291aKhJlw": f"{NON_KEY_DESC}, IODeviceTree:/buttons, starts with f, RingerButtonCapability",
    "SIC/2YcTF6ydv8Hfcn9THw": f"{NON_KEY_DESC}, IODeviceTree:/arm-io/aop/iop-aop-nub/als, starts with a, DisplayInactiveBrightnessClass",
    "SLu4aVo/V1CulJ7eyTDh1w": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with e, DeviceSupportsEnvironmentalDosimetry",
    "smT9LjRW3acTT7WTS/XqyQ": f"{NON_KEY_DESC}, IODeviceTree:/product/camera, starts with f, FrontFacingCameraHFRVideoCapture1080pMaxFPS",
    "t56wS9db+T2F2bxBpYSX8Q": f"{NON_KEY_DESC}, IODeviceTree:/arm-io/disp0, starts with e, DisplayDriverICChipID",
    "twWCmmM9I0dxwv7Zs9v48Q": f"{NON_KEY_DESC}, IODeviceTree:/product/audio, starts with a, DeviceSupportseARC",
    "uNNFSosc1xQM/7bwlrqLXA": f"{NON_KEY_DESC}, IODeviceTree:/arm-io/aop/iop-aop-nub/als, starts with m, DisplayMaxNits",
    "us1armjE6TKGvh2WIrNgEQ": f"{NON_KEY_DESC}, IODeviceTree:/defaults, starts with a, AlwaysOnDisplayMaxMemory",
    "vQg8hRTy1PC2j9L+8Jd+vg": f"{NON_KEY_DESC}, IODeviceTree:/product/audio, starts with s, DeviceSupportsVoiceOverCanUseSiriVoice",
    "wAbB2fAjUqUc6lNBelfWMA": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with n, DeviceSupportsPeriodicALSUpdates",
    "xgs6iXf0KFHUJ9d4FKaRYg": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with s, DeviceSupportsGrey",
    "yeQy+rgNoD7+YIY6mSVOhg": f"{NON_KEY_DESC}, IODeviceTree:/opal, starts with e",
    "Zg7DduDoSCy6vY6mhy3n2w": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with i, DeviceSupportsDynamicIsland",
}

known_keys_desc = {
    "/2V8H9h/+z0UxNUr9aRLeQ": NON_KEY_DESC,
    "/cMWdoU/88pcjJ1egxmIYw": NON_KEY_DESC,
    "/ej/HWmqnKV/QQptXhUZmg": NON_KEY_DESC,
    "/l0Kz2akvSvEHTNmZeY0nQ": NON_KEY_DESC,
    "/wG6EG34fRtAsZoLk/8YIw": NON_KEY_DESC,
    "/ZdBovdn5DLfkQkSAuAskw": NON_KEY_DESC,
    "+fgL2ovGydvB5CWd1JI1qg": NON_KEY_DESC,
    "+q5wYk81dLM2qjufnC0phw": NON_KEY_DESC,
    "+U0jSj4F2EfE+Vqj22IavA": NON_KEY_DESC,
    "+VTSncKV5ykgl9KAsuHFFg": NON_KEY_DESC,
    "+xJ6RaQ6PDSsLjib8r5fgg": NON_KEY_DESC,
    "0/QVFV5/X0h5iDjrdYYcog": NON_KEY_DESC,
    "0gkWjKWKuS2gqzTaFHKxqw": NON_KEY_DESC,
    "0vvGMT0ltmG03nFfaXxoHg": NON_KEY_DESC,
    "1oUugT++JJx5gOVyB2la7w": NON_KEY_DESC,
    "1z6Kk4xUAVLdaBPGugsDSA": NON_KEY_DESC,
    "2aIAScwtFNCz+Y7WesMOCA": NON_KEY_DESC,
    "2lNKobEIQqX50ohy1JBqCA": NON_KEY_DESC,
    "2v9hQi8xVAKZZVCMd/YhjQ": NON_KEY_DESC,
    "2ViNo1fbaEkg2vdTmCiW7g": NON_KEY_DESC,
    "3hD7TZt4FFvCgra7E8PkWw": NON_KEY_DESC,
    "3Hj0jFscGt094g65Fag7eQ": NON_KEY_DESC,
    "3sF/uRq+X+mZ2zGHSJOwpw": NON_KEY_DESC,
    "3uw7204ET4Vk1Cl4iJiNqQ": NON_KEY_DESC,
    "4+ntrbAfaq8rQKPfQo16CQ": NON_KEY_DESC,
    "4eFYRO4KDf8py/Zf3iHWZw": NON_KEY_DESC,
    "4JalTKSe5a9I+mb00ATvag": NON_KEY_DESC,
    "4k6Wv56SWfITjzet+hIHMQ": NON_KEY_DESC,
    "4OThI5F+/uP2oXUpdDxGnw": NON_KEY_DESC,
    "5/NbwB1egBxY8gECPU4nPA": NON_KEY_DESC,
    "50/CmBTX6jhkb8Z61hzwhQ": NON_KEY_DESC,
    "5dyhCh3dm1vSOaNK+US1Qw": NON_KEY_DESC,
    "5iilxso47rYJZGnXklkYYg": NON_KEY_DESC,
    "6PkKE66MnKm0yiOIQLknEg": NON_KEY_DESC,
    "6Y9R9JVBWd2wTX5ZdDGsWA": NON_KEY_DESC,
    "7ot70MKj7EdRIEEi91jlcg": NON_KEY_DESC,
    "7pq6UGJM2TaOP2brCspvyA": NON_KEY_DESC,
    "7qHcAWI5X9b1SiyYIg/Byw": NON_KEY_DESC,
    "7zSkleuS91WkyAuEEH7p2g": NON_KEY_DESC,
    "86GizkmSK+IxgCtUMOp2NA": NON_KEY_DESC,
    "8vIFqHe5lcMGo7TvbNLmyg": NON_KEY_DESC,
    "8Wunmi1SpU1MxfBxkv3KOw": NON_KEY_DESC,
    "9Bp5z20HsA1f7dqvelXKXA": NON_KEY_DESC,
    "9RreaA6rTvewPbqQy5ldRg": NON_KEY_DESC,
    "aCuWsar9Ayou7Vfkh7fdLw": NON_KEY_DESC,
    "Ah5yfSlY2yycIQb92HbmrA": NON_KEY_DESC,
    "aH78kNnsHDm9yHe6vSJYNw": NON_KEY_DESC,
    "aHrkhDFY/f2ophZ5/MqX0w": NON_KEY_DESC,
    "Ai0zsJQ3+sTFkU6/lLbd5A": NON_KEY_DESC,
    "aIJva0DAnD6KdrSpPF11xQ": NON_KEY_DESC,
    "aL9+NE29t3Wm2lEAE+atZQ": NON_KEY_DESC,
    "aNFMPe3XMOjAHDzk1h0eeA": NON_KEY_DESC,
    "aNZeCyuWxI6SE/KwZ129wA": NON_KEY_DESC,
    "AzZxA+yTHLc+/XimTirrVw": NON_KEY_DESC,
    "b/k0ZT2f/WGV2qJSyPJHoQ": NON_KEY_DESC,
    "b/KizANb5o/dWqSP2GC23g": NON_KEY_DESC,
    "b5K3g59Aj+Cc982n9FQv8A": NON_KEY_DESC,
    "bG+mTz0gYzxMfCms9/WzlQ": NON_KEY_DESC,
    "BGIXXp6VsbLlQg+8+0sBAA": NON_KEY_DESC,
    "BjJV766k5l7T4e9KHEKuBw": NON_KEY_DESC,
    "bmYssgjtQNKMy3Zhf8N+2w": NON_KEY_DESC,
    "brr2lQq9584zVkiuALaADA": NON_KEY_DESC,
    "BYYil6kIk8Hm5lRuA1k8Tw": NON_KEY_DESC,
    "c2ZyLSF00uEyREloINiqVA": NON_KEY_DESC,
    "cganRwxlDnONJx4WeDI0kQ": NON_KEY_DESC,
    "ch7KBY7aSsznfICVzjFldw": NON_KEY_DESC,
    "cmkS/KVB6ubxH76sLbumbw": NON_KEY_DESC,
    "D6PT05dEJ0f9Ayk7Yi92RA": NON_KEY_DESC,
    "dbYxhQWXkJhjp8uPhoMDvw": NON_KEY_DESC,
    "DCy89X5oErFAps95GX38mQ": NON_KEY_DESC,
    "DIXX7JMbm7glu49f+xi4zQ": NON_KEY_DESC,
    "e9aZViEIJ/riA4pRfg1ihg": NON_KEY_DESC,
    "edlvEg0UXOGErRDpk7O5Fg": NON_KEY_DESC,
    "EJRyIpTkLz2+Lb6XWy10bQ": NON_KEY_DESC,
    "eKgHzGQ9HnWdPKX7W16OAg": NON_KEY_DESC,
    "ESA7FmyB3KbJFNBAsBejcg": NON_KEY_DESC,
    "EuGnCiDhD1LBnMc96k/GQQ": NON_KEY_DESC,
    "F2M6lgy8EHCyR6hc00hMcg": NON_KEY_DESC,
    "F6wqOqCR9tpYWyB1taxxnw": NON_KEY_DESC,
    "Fam17Ufz3CiHdZPcma0AeQ": NON_KEY_DESC,
    "fb+1apeTeouqt+fo3nZ6sg": NON_KEY_DESC,
    "FQHZ8VqG8mVzDQ+g085l8w": NON_KEY_DESC,
    "FuR7SfqQmxpRW5MyqMm7FQ": NON_KEY_DESC,
    "fxnMXVRwuznDzWhoDCxb2A": NON_KEY_DESC,
    "g1gP4TOlkv84ezeaZrUgFg": NON_KEY_DESC,
    "g7yZjVHqRxbfXOqns+Sm9w": NON_KEY_DESC,
    "gJ3kBkjdqJ04oSsOmC97aw": NON_KEY_DESC,
    "gk8sn5Vi0s088gEvssfbOg": NON_KEY_DESC,
    "GnhnHyRVCC8LUClgElhKXA": NON_KEY_DESC,
    "gukw/2mRLE2GyqXJFEu7ng": NON_KEY_DESC,
    "h0OUwg53vKp+IPdzLG4NrA": NON_KEY_DESC,
    "h9v96tCehBWUil/aJ7UrcA": NON_KEY_DESC,
    "hh/NoWpEoq1VF4lGDdPUpw": NON_KEY_DESC,
    "hK/qlAUuu8u6SvIRkKmjQQ": NON_KEY_DESC,
    "hRBbURJnULvXsPGk42A8Ng": NON_KEY_DESC,
    "I+ptihXW+rMeySVUWURNiw": NON_KEY_DESC,
    "I6rd1SCXpRqBMDTPBbcWzA": NON_KEY_DESC,
    "i6wlxJoKNXBiVXJHJ1EHBg": NON_KEY_DESC,
    "I83EgnDEGxinSKU4QAykmA": NON_KEY_DESC,
    "IFHQSJ65DoElWQl/+eCfNQ": NON_KEY_DESC,
    "iifCuJmggYlB4hLzc0Zoiw": NON_KEY_DESC,
    "IMlsLCL69XUZau9QyPnxeQ": NON_KEY_DESC,
    "Ini7+h7Q4ZZctfFM9+KTBw": NON_KEY_DESC,
    "ItOvlwIhFj2aCXL4wk3ijg": NON_KEY_DESC,
    "IUvPFaILUl3l0684dR0AlA": NON_KEY_DESC,
    "IvdL59ITgJvhb5ptpLbqRg": NON_KEY_DESC,
    "J/a5Y6rhDH0gVkYtWUylOA": NON_KEY_DESC,
    "jkRyJt34tZOjsO1YhVc0mw": NON_KEY_DESC,
    "JOlwW/P8Cw3CDCoFunq8og": NON_KEY_DESC,
    "JQr1mcESYcN648vrcZPJEA": NON_KEY_DESC,
    "jw9WzWmThYzveJbsV+GZMA": NON_KEY_DESC,
    "K0tZN4PayAx7RgB0M+oohw": NON_KEY_DESC,
    "kc+QzHP4Frf2NvP+mclQ2A": NON_KEY_DESC,
    "KFwMMyiMoa8pLgGLwo78Vw": NON_KEY_DESC,
    "KLB4sM/KC38QT+dTuDC/aA": NON_KEY_DESC,
    "KN7t4gQkyj5X66dBpmh9HQ": NON_KEY_DESC,
    "knoZzQDWpu6OQWS7wgRWLg": NON_KEY_DESC,
    "kQ8nm82jb5iTBUwT2M3aIQ": NON_KEY_DESC,
    "l1MfXa14uBR9cvO8D9wc9w": NON_KEY_DESC,
    "LDmYwbIay7HexqftCTLDNg": NON_KEY_DESC,
    "lICl1+LV8GYEzQPilmyIXg": NON_KEY_DESC,
    "LL1FDn5UwIi7sIDnL19gxA": NON_KEY_DESC,
    "lMKshPs7fX9YxDSOEXnoiw": NON_KEY_DESC,
    "LMvmpCFM38ZaFeEy4r7nNQ": NON_KEY_DESC,
    "lNtvJFI6kdcchIbskQDzaA": NON_KEY_DESC,
    "lOIgg/0YE73mNKAiUbUiWQ": NON_KEY_DESC,
    "Lu6Mgo1O0+EoGMk1OtnMRg": NON_KEY_DESC,
    "lvmEUCUwik8sO0yGU1rBOA": NON_KEY_DESC,
    "LWxSM4CmFZMwzYclSh43gg": NON_KEY_DESC,
    "LXP9TbNYtZrIKOktGXez2Q": NON_KEY_DESC,
    "lY6RKv6ri6kfBeJCWilmmQ": NON_KEY_DESC,
    "M+eWZ6Zk/aJIsnIrv4zdAg": NON_KEY_DESC,
    "MfLtAGqrSIJgBHzuir/DoA": NON_KEY_DESC,
    "mH5IrpyGkVtmgdqs68KHRg": NON_KEY_DESC,
    "Mif7940cFpfaXIAHwkYgHQ": NON_KEY_DESC,
    "MlDJggkQz38CLQh3AVv7VQ": NON_KEY_DESC,
    "mm4/5+X4Z+eStXyipfwWVQ": NON_KEY_DESC,
    "MQoTKg93BM8ZhBaB3WUPdw": NON_KEY_DESC,
    "MvBKQ+GSnR3DjkovgNL+3w": NON_KEY_DESC,
    "MXZ7vg7hul895QdsLUBJFA": NON_KEY_DESC,
    "MzxVeXMzucmEMx2lw8Pg1Q": NON_KEY_DESC,
    "N6PmkZnK1VRMvFokb0jS/Q": NON_KEY_DESC,
    "na77zbwlhy0V7shc4ORRgA": NON_KEY_DESC,
    "NKo9tzEYqtHAfQYMFsc66Q": NON_KEY_DESC,
    "NkQOJZ1xdFk5SV55PFKlIg": NON_KEY_DESC,
    "NlddTE7HnMJiw5OzTqbrYA": NON_KEY_DESC,
    "npI2l0ybDY9Um4z/T8K/Sg": NON_KEY_DESC,
    "NsIeRLGugrogpTZiayi1VA": NON_KEY_DESC,
    "nudr7/i2XcxAX6widrWShg": NON_KEY_DESC,
    "OCKVZEIuMz4sxhLz7vmQ5w": NON_KEY_DESC,
    "OJTdSHEAfpOvV6m6o+Ou1w": NON_KEY_DESC,
    "OmiBcaNEpjOcuQrO5/Yrbw": NON_KEY_DESC,
    "OtnrTIhWBtyPo45BcApMTw": NON_KEY_DESC,
    "oTuH4/axV9s11/jKxB2z2A": NON_KEY_DESC,
    "Ov9G2lRzQYbUyBYJ0KCMhA": NON_KEY_DESC,
    "oxH8p7+EaUzhkc2edrXsQQ": NON_KEY_DESC,
    "P+UqVuzQzn3nwHSiSeDmyw": NON_KEY_DESC,
    "P1uSdgM/fIttMsA/+q6k4w": NON_KEY_DESC,
    "pdFo85PUvIiT4FjAT6Amcw": NON_KEY_DESC,
    "PgQhOQ4/ZYPLM6mgAoPm4A": NON_KEY_DESC,
    "PNIwPfoxY6URyv3kSma5Aw": NON_KEY_DESC,
    "PT6XKHaOkrxhQTpTVI8Rlw": NON_KEY_DESC,
    "pxqIJ789zCoOILWO6cQ52Q": NON_KEY_DESC,
    "Q/BI7GKNZY13TpxbqA8nhQ": NON_KEY_DESC,
    "Q2y7EshBFzIifIPKAPVBBA": NON_KEY_DESC,
    "Q4b8YIwPgnznT5hs4qXjaA": NON_KEY_DESC,
    "QD3Nde07fjdK0R0KTbczEA": NON_KEY_DESC,
    "Qt+S0J/SXrcfymyfJWvCCQ": NON_KEY_DESC,
    "r/++Z94rbTcHrTtZ/rCU4w": NON_KEY_DESC,
    "R1AF5xVFhlNjSbjBZJqQeA": NON_KEY_DESC,
    "R1tbjTooZCgq2KmzlTaX+g": NON_KEY_DESC,
    "RaX3KBmG7H9fUOEtLK/I6w": NON_KEY_DESC,
    "RIJvT6s+kyJKsCvHFbcwwA": NON_KEY_DESC,
    "RN/FxX/3jy6LWaEIPR8qpA": NON_KEY_DESC,
    "RN4AimpWqqD2JZCB67qtvQ": NON_KEY_DESC,
    "RR4G+l3k5mfFFr6Igw88kQ": NON_KEY_DESC,
    "RrhB72r1de9N65EG4pgqJw": NON_KEY_DESC,
    "rwnje21oPXH375umjxV6YQ": NON_KEY_DESC,
    "S5Bf9bF00BTHrySCydAkdg": NON_KEY_DESC,
    "sBBgbCSIQcUOXwgaDW/Xew": NON_KEY_DESC,
    "SKBEzVsOS9Wr/WlkVtlUMQ": NON_KEY_DESC,
    "Sr1Bmb3uoIfgKyaZguG0Gw": NON_KEY_DESC,
    "sYxZdpH3i8nwjZNet0QuAw": NON_KEY_DESC,
    "T9MMpvl0fu59PO8lXi/Cxg": NON_KEY_DESC,
    "tAryHM5IUMkdtvVqqu1tcA": NON_KEY_DESC,
    "tOLVnZop4m/g5/iuC7zlUw": NON_KEY_DESC,
    "TucF/tpjeAln1I0f3g0K3w": NON_KEY_DESC,
    "U1fcnNYCEu9uH1bg3/6PKQ": NON_KEY_DESC,
    "UF3CoK9RCYXfTyzttoxNDQ": NON_KEY_DESC,
    "UYZtXbMcIyMRZQ9pjDxRvA": NON_KEY_DESC,
    "v/BP9Nx/zfo9bKi9JR2p+g": NON_KEY_DESC,
    "v1/EHDarbU55OfoXm2EiGA": NON_KEY_DESC,
    "v7h4TrJdmukTl8gpzVl3DQ": NON_KEY_DESC,
    "vmZuX/fdqt3gKhonHYLyUw": NON_KEY_DESC,
    "voS/bmBAz0Y1eNLoN8x9/Q": NON_KEY_DESC,
    "vq2wpvLzyYLEApQs9cs52A": NON_KEY_DESC,
    "VrWzQGQK9Fbp/RqeQ08VzA": NON_KEY_DESC,
    "vTKPWiAZkQifTv/4/uOnQQ": NON_KEY_DESC,
    "W5kTfIuxkKpHVdWTk42C9A": NON_KEY_DESC,
    "WbcphnnzI6Yb5r/AzwiyUA": NON_KEY_DESC,
    "X9NA3D+PguwY0i0Uffl07Q": NON_KEY_DESC,
    "XEp4h49dagkYL6YrtjW1Kw": NON_KEY_DESC,
    "XKpK5v7PGzbe7igjloNBpQ": NON_KEY_DESC,
    "xXBT4e92qXwQo3SYmACj3w": NON_KEY_DESC,
    "XyppJjhSQE2982ZYgXlh2g": NON_KEY_DESC,
    "y66yh6E28lG6AIdLLwEvSQ": NON_KEY_DESC,
    "YcNAX0Gc6KejQPKSrA9kvg": NON_KEY_DESC,
    "yeaE9+OrN2WJlWkDroMtZg": NON_KEY_DESC,
    "yhZxZlqgBWwf4bN9t6fFyA": NON_KEY_DESC,
    "Yk5H+MlMreeaBLjv6PPFDw": NON_KEY_DESC,
    "yPSUYPhrVLHnvX0TUugiwg": NON_KEY_DESC,
    "ZcPQWuQwUJtMR5Oj99uc8w": NON_KEY_DESC,
    "zDBaE8nqtDP8hY4pOa6iMw": NON_KEY_DESC,
    "Zhoou87qmFpFwcFsm7Jlyg": NON_KEY_DESC,
    "zJUWenIp94snlzBD1cub3g": NON_KEY_DESC,
    "znvmheFkjr6hiqIK9TrCVw": NON_KEY_DESC,
    "ZrKzmIA8JSV7qJtGrX3yIw": NON_KEY_DESC,
    "ZT0Z0SqGF/esuJWDmk8mGw": NON_KEY_DESC,
}
