NON_KEY_DESC = 'non-gestalt-key'

unknown_keys_desc = {
    "+xJ6RaQ6PDSsLjib8r5fgg": f"{NON_KEY_DESC}, IODeviceTree:/product/camera, starts with p, DeviceSupportsCameraCaptureOnTouchDown",
    "0gkWjKWKuS2gqzTaFHKxqw": f"{NON_KEY_DESC}, IODeviceTree/product/audio, starts with s, DeviceSupportsAdvancedVoiceProcessorChatFlavor",
    "1HWDBfJwBJZ8TDHcPDafmQ": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with e, DeviceHasEmbeddedSIMOnlyBoard",
    "2aIAScwtFNCz+Y7WesMOCA": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with m, SecondaryWifiMacAddressData",
    "2v9hQi8xVAKZZVCMd/YhjQ": f"{NON_KEY_DESC}, IODeviceTree:/product/audio, starts with s, DeviceSupportsSiriBargeIn",
    "3Hj0jFscGt094g65Fag7eQ": f"{NON_KEY_DESC}, Hardware platform, starts with t",
    "4eFYRO4KDf8py/Zf3iHWZw": f"{NON_KEY_DESC}, IODeviceTree:/product/audio, starts with s, SpeakerCalibrationSpTs",
    "8Kc1MRjWTfDiGKX6E/9XqQ": f"{NON_KEY_DESC}, IODeviceTree:/product/audio, starts with l, DeviceSupportsLongFormAudio",
    "8kcKPCGGyCpf66MMl5TVkA": f"{NON_KEY_DESC}, IODeviceTree:/multi-touch, starts with m, MultiTouchMaxBootTime",
    "bbyFCcrPE+k6ZXIVbXSFUw": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with u, DevicePrefersBuildingStrokes",
    "bG+mTz0gYzxMfCms9/WzlQ": f"{NON_KEY_DESC}, IODeviceTree:/product/camera, starts with r, RearFacingCameraSuperWideCameraCapability",
    "bxQyyA/qJ3QQXTiHBsW2eg": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with o, BuddyLanguagesAnimationRequiresOptimization",
    "dUipfYkyvM80t4IkmMBVgQ": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with w, DeviceSupportsElton",
    "HhLXszMhK6bb9TP4sqVQWQ": f"{NON_KEY_DESC}, IODeviceTree:/chosen, starts with e, ExtendedSecurityDomain",
    "jkRyJt34tZOjsO1YhVc0mw": f"{NON_KEY_DESC}, IODeviceTree:/product/audio, starts with s, AutomaticMicMode",
    "mug/QuG6jZ3CYR9p7OWQaw": f"{NON_KEY_DESC}, IODeviceTree:/opal, starts with b",
    "oOV1jhJbdV3AddkcCg0AEA": "MetalPerfLevelCapabilityOne4IOS (mismatched)",
    "QY61T8CLLwG/yu92ScTYtw": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with s, driverkit",
    "R1AF5xVFhlNjSbjBZJqQeA": f"{NON_KEY_DESC}, IODeviceTree:/product/camera, starts with r, RearFacingCameraStageLightPortraitCaptureCapability",
    "R1tbjTooZCgq2KmzlTaX+g": f"{NON_KEY_DESC}, IODeviceTree:/product/camera, starts with f, FrontFacingCameraStageLightPortraitCaptureCapability",
    "sad18VQX7AeS+291aKhJlw": f"{NON_KEY_DESC}, IODeviceTree:/buttons, starts with f, RingerButtonCapability",
    "t56wS9db+T2F2bxBpYSX8Q": f"{NON_KEY_DESC}, IODeviceTree:/arm-io/disp0, starts with e, DisplayDriverICChipID",
    "twWCmmM9I0dxwv7Zs9v48Q": f"{NON_KEY_DESC}, IODeviceTree:/product/audio, starts with a, DeviceSupportseARC",
    "uNNFSosc1xQM/7bwlrqLXA": f"{NON_KEY_DESC}, IODeviceTree:/arm-io/aop/iop-aop-nub/als, starts with m, DisplayMaxNits",
    "us1armjE6TKGvh2WIrNgEQ": f"{NON_KEY_DESC}, IODeviceTree:/defaults, starts with a, AlwaysOnDisplayMaxMemory",
    "voS/bmBAz0Y1eNLoN8x9/Q": f"{NON_KEY_DESC}, IODeviceTree:/product/camera, starts with p, front-depth-camera",
    "vQg8hRTy1PC2j9L+8Jd+vg": f"{NON_KEY_DESC}, IODeviceTree:/product/audio, starts with s, DeviceSupportsVoiceOverCanUseSiriVoice",
    "vTKPWiAZkQifTv/4/uOnQQ": f"{NON_KEY_DESC}, IODeviceTree:/product/camera, starts with f, FrontFacingCameraSuperWideCameraCapability",
    "wAbB2fAjUqUc6lNBelfWMA": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with n, DeviceSupportsPeriodicALSUpdates",
    "xgs6iXf0KFHUJ9d4FKaRYg": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with s, DeviceSupportsGrey",
    "yeQy+rgNoD7+YIY6mSVOhg": f"{NON_KEY_DESC}, IODeviceTree:/opal, starts with e",
    "Zg7DduDoSCy6vY6mhy3n2w": f"{NON_KEY_DESC}, IODeviceTree:/product, starts with i, DeviceSupportsDynamicIsland",
}

known_keys_desc = {
    "/2V8H9h/+z0UxNUr9aRLeQ": NON_KEY_DESC,
    "/cMWdoU/88pcjJ1egxmIYw": NON_KEY_DESC,
    "/ej/HWmqnKV/QQptXhUZmg": NON_KEY_DESC,
    "/l0Kz2akvSvEHTNmZeY0nQ": NON_KEY_DESC,
    "/wG6EG34fRtAsZoLk/8YIw": NON_KEY_DESC,
    "/ZdBovdn5DLfkQkSAuAskw": NON_KEY_DESC,
    "+fgL2ovGydvB5CWd1JI1qg": NON_KEY_DESC,
    "+q5wYk81dLM2qjufnC0phw": NON_KEY_DESC,
    "+U0jSj4F2EfE+Vqj22IavA": NON_KEY_DESC,
    "+VTSncKV5ykgl9KAsuHFFg": NON_KEY_DESC,
    "0/QVFV5/X0h5iDjrdYYcog": NON_KEY_DESC,
    "0vvGMT0ltmG03nFfaXxoHg": NON_KEY_DESC,
    "1oUugT++JJx5gOVyB2la7w": NON_KEY_DESC,
    "2ViNo1fbaEkg2vdTmCiW7g": NON_KEY_DESC,
    "3hD7TZt4FFvCgra7E8PkWw": NON_KEY_DESC,
    "3Hj0jFscGt094g65Fag7eQ": NON_KEY_DESC,
    "3sF/uRq+X+mZ2zGHSJOwpw": NON_KEY_DESC,
    "3uw7204ET4Vk1Cl4iJiNqQ": NON_KEY_DESC,
    "4+ntrbAfaq8rQKPfQo16CQ": NON_KEY_DESC,
    "4JalTKSe5a9I+mb00ATvag": NON_KEY_DESC,
    "4k6Wv56SWfITjzet+hIHMQ": NON_KEY_DESC,
    "4OThI5F+/uP2oXUpdDxGnw": NON_KEY_DESC,
    "5/NbwB1egBxY8gECPU4nPA": NON_KEY_DESC,
    "50/CmBTX6jhkb8Z61hzwhQ": NON_KEY_DESC,
    "5dyhCh3dm1vSOaNK+US1Qw": NON_KEY_DESC,
    "5iilxso47rYJZGnXklkYYg": NON_KEY_DESC,
    "6PkKE66MnKm0yiOIQLknEg": NON_KEY_DESC,
    "6Y9R9JVBWd2wTX5ZdDGsWA": NON_KEY_DESC,
    "7pq6UGJM2TaOP2brCspvyA": NON_KEY_DESC,
    "7qHcAWI5X9b1SiyYIg/Byw": NON_KEY_DESC,
    "7zSkleuS91WkyAuEEH7p2g": NON_KEY_DESC,
    "86GizkmSK+IxgCtUMOp2NA": NON_KEY_DESC,
    "8Wunmi1SpU1MxfBxkv3KOw": NON_KEY_DESC,
    "9Bp5z20HsA1f7dqvelXKXA": NON_KEY_DESC,
    "9RreaA6rTvewPbqQy5ldRg": NON_KEY_DESC,
    "aCuWsar9Ayou7Vfkh7fdLw": NON_KEY_DESC,
    "Ah5yfSlY2yycIQb92HbmrA": NON_KEY_DESC,
    "aHrkhDFY/f2ophZ5/MqX0w": NON_KEY_DESC,
    "Ai0zsJQ3+sTFkU6/lLbd5A": NON_KEY_DESC,
    "aIJva0DAnD6KdrSpPF11xQ": NON_KEY_DESC,
    "aL9+NE29t3Wm2lEAE+atZQ": NON_KEY_DESC,
    "aNFMPe3XMOjAHDzk1h0eeA": NON_KEY_DESC,
    "aNZeCyuWxI6SE/KwZ129wA": NON_KEY_DESC,
    "b/k0ZT2f/WGV2qJSyPJHoQ": NON_KEY_DESC,
    "b/KizANb5o/dWqSP2GC23g": NON_KEY_DESC,
    "BGIXXp6VsbLlQg+8+0sBAA": NON_KEY_DESC,
    "BjJV766k5l7T4e9KHEKuBw": NON_KEY_DESC,
    "bmYssgjtQNKMy3Zhf8N+2w": NON_KEY_DESC,
    "brr2lQq9584zVkiuALaADA": NON_KEY_DESC,
    "BYYil6kIk8Hm5lRuA1k8Tw": NON_KEY_DESC,
    "c2ZyLSF00uEyREloINiqVA": NON_KEY_DESC,
    "cmkS/KVB6ubxH76sLbumbw": NON_KEY_DESC,
    "D6PT05dEJ0f9Ayk7Yi92RA": NON_KEY_DESC,
    "DIXX7JMbm7glu49f+xi4zQ": NON_KEY_DESC,
    "edlvEg0UXOGErRDpk7O5Fg": NON_KEY_DESC,
    "EJRyIpTkLz2+Lb6XWy10bQ": NON_KEY_DESC,
    "eKgHzGQ9HnWdPKX7W16OAg": NON_KEY_DESC,
    "ESA7FmyB3KbJFNBAsBejcg": NON_KEY_DESC,
    "F6wqOqCR9tpYWyB1taxxnw": NON_KEY_DESC,
    "g7yZjVHqRxbfXOqns+Sm9w": NON_KEY_DESC,
    "gk8sn5Vi0s088gEvssfbOg": NON_KEY_DESC,
    "gukw/2mRLE2GyqXJFEu7ng": NON_KEY_DESC,
    "hh/NoWpEoq1VF4lGDdPUpw": NON_KEY_DESC,
    "hRBbURJnULvXsPGk42A8Ng": NON_KEY_DESC,
    "I83EgnDEGxinSKU4QAykmA": NON_KEY_DESC,
    "iifCuJmggYlB4hLzc0Zoiw": NON_KEY_DESC,
    "IMlsLCL69XUZau9QyPnxeQ": NON_KEY_DESC,
    "Ini7+h7Q4ZZctfFM9+KTBw": NON_KEY_DESC,
    "IUvPFaILUl3l0684dR0AlA": NON_KEY_DESC,
    "JOlwW/P8Cw3CDCoFunq8og": NON_KEY_DESC,
    "JQr1mcESYcN648vrcZPJEA": NON_KEY_DESC,
    "jw9WzWmThYzveJbsV+GZMA": NON_KEY_DESC,
    "KLB4sM/KC38QT+dTuDC/aA": NON_KEY_DESC,
    "knoZzQDWpu6OQWS7wgRWLg": NON_KEY_DESC,
    "lMKshPs7fX9YxDSOEXnoiw": NON_KEY_DESC,
    "lNtvJFI6kdcchIbskQDzaA": NON_KEY_DESC,
    "Lu6Mgo1O0+EoGMk1OtnMRg": NON_KEY_DESC,
    "lvmEUCUwik8sO0yGU1rBOA": NON_KEY_DESC,
    "LWxSM4CmFZMwzYclSh43gg": NON_KEY_DESC,
    "lY6RKv6ri6kfBeJCWilmmQ": NON_KEY_DESC,
    "M+eWZ6Zk/aJIsnIrv4zdAg": NON_KEY_DESC,
    "MfLtAGqrSIJgBHzuir/DoA": NON_KEY_DESC,
    "mH5IrpyGkVtmgdqs68KHRg": NON_KEY_DESC,
    "MlDJggkQz38CLQh3AVv7VQ": NON_KEY_DESC,
    "MQoTKg93BM8ZhBaB3WUPdw": NON_KEY_DESC,
    "MXZ7vg7hul895QdsLUBJFA": NON_KEY_DESC,
    "MzxVeXMzucmEMx2lw8Pg1Q": NON_KEY_DESC,
    "N6PmkZnK1VRMvFokb0jS/Q": NON_KEY_DESC,
    "NKo9tzEYqtHAfQYMFsc66Q": NON_KEY_DESC,
    "NkQOJZ1xdFk5SV55PFKlIg": NON_KEY_DESC,
    "NsIeRLGugrogpTZiayi1VA": NON_KEY_DESC,
    "OJTdSHEAfpOvV6m6o+Ou1w": NON_KEY_DESC,
    "OmiBcaNEpjOcuQrO5/Yrbw": NON_KEY_DESC,
    "oTuH4/axV9s11/jKxB2z2A": NON_KEY_DESC,
    "P1uSdgM/fIttMsA/+q6k4w": NON_KEY_DESC,
    "PNIwPfoxY6URyv3kSma5Aw": NON_KEY_DESC,
    "Q/BI7GKNZY13TpxbqA8nhQ": NON_KEY_DESC,
    "Q4b8YIwPgnznT5hs4qXjaA": NON_KEY_DESC,
    "Qt+S0J/SXrcfymyfJWvCCQ": NON_KEY_DESC,
    "r/++Z94rbTcHrTtZ/rCU4w": NON_KEY_DESC,
    "RaX3KBmG7H9fUOEtLK/I6w": NON_KEY_DESC,
    "RIJvT6s+kyJKsCvHFbcwwA": NON_KEY_DESC,
    "RrhB72r1de9N65EG4pgqJw": NON_KEY_DESC,
    "rwnje21oPXH375umjxV6YQ": NON_KEY_DESC,
    "Sr1Bmb3uoIfgKyaZguG0Gw": NON_KEY_DESC,
    "sYxZdpH3i8nwjZNet0QuAw": NON_KEY_DESC,
    "tAryHM5IUMkdtvVqqu1tcA": NON_KEY_DESC,
    "tOLVnZop4m/g5/iuC7zlUw": NON_KEY_DESC,
    "UF3CoK9RCYXfTyzttoxNDQ": NON_KEY_DESC,
    "v1/EHDarbU55OfoXm2EiGA": NON_KEY_DESC,
    "v7h4TrJdmukTl8gpzVl3DQ": NON_KEY_DESC,
    "vmZuX/fdqt3gKhonHYLyUw": NON_KEY_DESC,
    "vq2wpvLzyYLEApQs9cs52A": NON_KEY_DESC,
    "W5kTfIuxkKpHVdWTk42C9A": NON_KEY_DESC,
    "WbcphnnzI6Yb5r/AzwiyUA": NON_KEY_DESC,
    "X9NA3D+PguwY0i0Uffl07Q": NON_KEY_DESC,
    "xXBT4e92qXwQo3SYmACj3w": NON_KEY_DESC,
    "XyppJjhSQE2982ZYgXlh2g": NON_KEY_DESC,
    "y66yh6E28lG6AIdLLwEvSQ": NON_KEY_DESC,
    "YcNAX0Gc6KejQPKSrA9kvg": NON_KEY_DESC,
    "yeaE9+OrN2WJlWkDroMtZg": NON_KEY_DESC,
    "yhZxZlqgBWwf4bN9t6fFyA": NON_KEY_DESC,
    "Yk5H+MlMreeaBLjv6PPFDw": NON_KEY_DESC,
    "yPSUYPhrVLHnvX0TUugiwg": NON_KEY_DESC,
    "ZcPQWuQwUJtMR5Oj99uc8w": NON_KEY_DESC,
    "zDBaE8nqtDP8hY4pOa6iMw": NON_KEY_DESC,
    "Zhoou87qmFpFwcFsm7Jlyg": NON_KEY_DESC,
    "znvmheFkjr6hiqIK9TrCVw": NON_KEY_DESC,
    "ZrKzmIA8JSV7qJtGrX3yIw": NON_KEY_DESC,
}
