#include "struct.h"

// Total: 907 keys
// Deobfuscated: 907 keys (100.0%)
// Unexplored: 0 keys

static const struct tKeyMapping keyMappingTable[] = {
    "+1TeoctsaQC55zwHZ6MESg", "ProductTypeDescForAudio", // iOS 26.0
    "+3Uf0Pm5F8Xy7Onyvko0vA", "DeviceClass", // iOS pre-12.0
    "+97cHA72jHlHqQnIkgGBYg", "CameraHDRVersion", // iOS 26.0-
    "+bL/lKwaIAv+fzmjsHYZdw", "N78aHack", // iOS pre-12.0
    "+Ce1uSqGUXaJPl/uT6ur8g", "SDIOProductInfo", // iOS pre-12.0
    "+N9mZUAHooNvMiQnjeTJ8g", "HasAppleNeuralEngine", // iOS pre-12.0
    "+VIu65zA5EW4ztayJXvOUg", "device-name-localized", // iOS pre-12.0
    "/6FWCRjN1yRdUABG9vF8ow", "WiFiCallingCapability", // iOS pre-12.0
    "/9luHerXthRoPoNt/PVkTg", "VibratorCapability", // iOS pre-12.0
    "/bfa1LxXd7G1WqHujpjsdA", "WatchSupportsMusicStreaming", // iOS pre-12.0
    "/bSMNaIuUT58N/BN1nYUjw", "airDropRestriction", // iOS pre-12.0
    "/EVOCjM/Nmb2roP5ebtEFA", "DeviceSupportsSpatialFaceTimeAudioPlayback", // iOS 26.0-
    "/GK+yfRFY/b5ZDIDpdVImg", "hardware-keyboard", // iOS pre-12.0
    "/Oajtq8qODrC4XBBOULF3A", "DeviceSupportsHeartRateVariability", // iOS pre-12.0
    "/oWN4fE81uA9pCW4FmD7Ug", "DeviceSupportsFrameSynchronousBrightness", // iOS 26.0-
    "/Pop5T2XQdDA60MRyxQJdQ", "hall-effect-sensor", // iOS pre-12.0
    "/YYygAofPDbhrwToVsXdeA", "HWModelStr", // iOS pre-12.0
    "0+nc/Udy4WNG8S+Q7a/s1A", "ThinningProductType", // iOS 26.0-
    "0/2HluYMd/whD80Hua4Rpw", "io-surface-backed-images", // iOS pre-12.0
    "0/7QNywWU4IqDcyvTv9UYQ", "RearFacingCameraVideoCapture720pMaxFPS", // iOS pre-12.0
    "0/VAyl58TL5U/mAQEJNRQw", "DeviceHasAggregateCamera", // iOS pre-12.0
    "03hWmMtMs+4nzama4/PzHQ", "CameraLiveEffectsCapability", // iOS pre-12.0
    "0AFeHRmliNJ4pSlVb8ltZA", "FrontFacingCameraVideoCapture720pMaxFPS", // iOS pre-12.0
    "0AJUv/uYPsRiZNGpWJ7zfg", "DeviceSupportsSiriSpokenMessages", // iOS 26.0-
    "0D3qCmmfJ/i1mpmjOsV7EA", "ScreenSerialNumber", // iOS 26.0-
    "0dnM19zBqLw5ZPhIo4GEkg", "SecureElement", // iOS pre-12.0
    "0GizaJLOyfzgAbxQ/5aniA", "DeviceHousingColorUncooked", // iOS 26.0-
    "0GUU+Z8xIu+7TE+scKXscg", "OysterCapability", // iOS 26.0-
    "0jjK6IVSQzA8doQeSwmujA", "software-bundle-version", // iOS pre-12.0
    "0KHhsv2F/BGA9AppFljmKg", "AttestationUniqueDeviceID", // iOS 26.0-
    "0l4wqBtWEAK1tOkeBHkU6Q", "main-screen-pitch", // iOS pre-12.0
    "0L5PkT61qoH1b/B1USWqjQ", "RegionalBehaviorChinaBrick", // iOS pre-12.0
    "0pY9r1XBV1duZ8HO3tBvFg", "location-services", // iOS pre-12.0
    "0R2aiV2nJVu/v8I7Ex2GcQ", "RegionalBehaviorNoPasscodeLocationTiles", // iOS pre-12.0
    "0rbLl0hXmTehfEduXfeJYQ", "ThreadRadioMacAddress", // iOS 26.0-
    "0uthiXrHZ212KvcJizKHEw", "BoardId", // iOS pre-12.0
    "0uyHvVqOLpJQBpSl/rF3Vg", "kSimultaneousCallAndDataSupported", // iOS pre-12.0
    "0VkTunHOJrrZdolQXR5gCg", "DevicePrefersTrafficAlpha", // iOS pre-12.0
    "0Y4fmR6ZHZPxDZFfPtBnRQ", "SysCfg", // iOS pre-12.0
    "0Yu30fwSQVPKvHVla17kXw", "umts-device", // iOS pre-12.0
    "16N2bLOzcgJEsZToEX21Zg", "accessibility", // iOS pre-12.0
    "1Bk5Dr0hTb0bYXl04068MQ", "DeviceSupportsTwilight", // iOS 26.0-
    "1CFbwvaGHR/89vDu2VjnpQ", "DeviceSupportsLowLatency", // iOS 26.0-
    "1cPL2NOPt23mHxhn0J4xPA", "DeviceSupportsGrayDimming", // iOS 26.0
    "1DQNgySZSIjPqLWroIzfiQ", "BacklightCapability", // iOS pre-12.0
    "1eBwtCIwbIDdC80wiyzfow", "DeviceSupportsP3ColorspaceVideoRecording", // iOS pre-12.0
    "1gsBzuZsXu2rXZJBE01M0w", "FrontFacingCameraHFRCapability", // iOS pre-12.0
    "1N14oS9TeyskaTU1DxpwoQ", "load-thumbnails-while-scrolling", // iOS pre-12.0
    "1N37hGont/jibw4G2hwdRg", "DeviceSupportsUnconditionalPluckItCollection", // iOS 26.0-
    "1oMPwMsqxTa9BJxUs8v06w", "PlatinumCapability", // iOS pre-12.0
    "1plD8faLv1bhScZQ3t0PLQ", "IsServicePart", // iOS 26.0-
    "1qDdT/85SS7sxriK0wIbbg", "main-screen-orientation", // iOS pre-12.0
    "1qJmMHedWOh43VwRKPdDrw", "iTunesFamilyID", // iOS pre-12.0
    "1rf3rZXIZFgznqrHlPehuQ", "FaceTimeBitRate3G", // iOS pre-12.0
    "1Rm/mWYEI5ttaC0dJ3sHBQ", "BootNonce", // iOS pre-12.0
    "1uZbhSbBhsNCsVSsopZ4qg", "dictation", // iOS pre-12.0
    "1X0zc2JwBdYOQrMAyP81DQ", "lte-device", // iOS pre-12.0
    "2/q9qmqGigMfkzY830Zf2g", "YonkersChipID", // iOS pre-12.0
    "2IDxmg5KyAMBBi/b0rojgQ", "telephony-maximum-generation", // iOS pre-12.0
    "2kuITg6XPwXl8zbpx+hoCw", "FrontFacingIRCameraModuleSerialNumber", // iOS pre-12.0
    "2OK50OGmkXM1ospsh766WQ", "TouchDelivery120Hz", // iOS pre-12.0
    "2oKaRZpltNseA9gTdIKTQQ", "tvos-perf-level-1", // iOS 26.0-
    "2OOJf1VhaM7NxfRok3HbWQ", "DeviceSupportsAlwaysOnDisplay", // iOS 26.0-
    "2pxKjejpRGpWvUE+3yp5mQ", "cameraRestriction", // iOS pre-12.0
    "2Qf/8sQyx6voo3Mw3QKgZQ", "DeviceRequiresSoftwareBrightnessCalculations", // iOS pre-12.0
    "2sWGezz2RezScIJJgiIYQg", "IcefallInRestrictedMode", // iOS pre-12.0
    "2tBx5IzZX4CpUVJ79LfsVg", "TribecaSettings", // iOS 26.0-
    "2xSqkUxsVWmOBWk6StVOfQ", "LunaFlexSerialNumber", // iOS pre-12.0
    "2zyzecwSf2ZYRpB3tuQhOQ", "DeviceSupportsWirelessSplitting", // iOS 26.0-
    "37NVydb//GP/GrhuTN+exg", "DeviceSupports80ChargeLimit", // iOS 26.0-
    "38C0kq9NiVaMsqjlUsCHcQ", "ota-activation", // iOS pre-12.0
    "39ZkJVEsL4pmCXbg+89QmQ", "accelerometer", // iOS pre-12.0
    "3kmXfug8VcxLI5yEmsqQKw", "InDiagnosticsMode", // iOS pre-12.0
    "3m1Q0AXlqeA2C/LmqdTndQ", "HasDaliMode", // iOS pre-12.0
    "3XvzxIDBOG+shuGoNFh1jQ", "UnifiedGamingPerfLevelMacTier1", // iOS 26.0
    "3yzXj0lJhQi+r3kgQlwiOg", "FrontFacingCameraVideoCapture1080pMaxFPS", // iOS pre-12.0
    "4+qmMh9JBDh72Nq6fD64RQ", "gyroscope", // iOS pre-12.0
    "475wW3fne+tyzGr4wleUSQ", "CarrierBundleInfoArray", // iOS pre-12.0
    "4D8XW4YwJI7QvyPhv1TEdw", "DeviceSupportsRaiseToSpeak", // iOS pre-12.0
    "4ec+Q3FdQ1N0HeNpOPsmfA", "DeviceSupportsThunderbolt", // iOS 26.0-
    "4fh9efw4o1yaFqkXNCXoeA", "DeviceSupportsHypertensivePatternMeasurements", // iOS 26.0
    "4fT83+9coO3VAUnlxuOOcw", "SupportsEDUMU", // iOS pre-12.0
    "4I0hOaR3n80379Vka7u+Xg", "volume-buttons", // iOS pre-12.0
    "4Jfu4lqX8dzru4Z+ONQ1rQ", "PhotosPostEffectsCapability", // iOS pre-12.0
    "4qfpxrvLtWillIHpIsVgMA", "SystemImageID", // iOS pre-12.0
    "4RgFi8v1sfuhCZhRdQkxxQ", "FaceTimePhotosOptIn", // iOS pre-12.0
    "4RwhtNOmePfUXmu57rh+KA", "LisaCapability", // iOS pre-12.0
    "4snMZS8LJkSctKypt2m+xA", "not-green-tea", // iOS pre-12.0
    "4szz4QLjIlB52alQ4J3R1g", "IsSimulatedDevice", // iOS 26.0
    "4uzgAFPkzKUmlZG5HpFIkg", "RegionalBehaviorGoogleMail", // iOS pre-12.0
    "4W7X4OWHjri5PGaAGsCWxw", "MaxH264PlaybackLevel", // iOS pre-12.0
    "52jOwM53SViDv1B3wZIIOg", "DeviceSupportsAdvancedVoiceProcessorChatFlavor", // iOS 26.0-
    "566JrJVMlDfnslGpwUzNlQ", "ChipID", // iOS pre-12.0
    "57eLnXynqDlQaGEi+9JAtQ", "call-forwarding", // iOS pre-12.0
    "5hfTRTYOuOthOyRny6a38w", "continuity-camera", // iOS 26.0-
    "5lAK1Xp+ezh1Qu+4jnHAOg", "SupportsSOS", // iOS pre-12.0
    "5MSZn7w3nnJp22VbpqaxLQ", "venice", // iOS pre-12.0
    "5mvQIwu3Mqqw/zOKmwGkWw", "ProximitySensorCalibrationDictionary", // iOS pre-12.0
    "5MXFoiW2zgxfIbaaTb/wvA", "SecondaryEthernetMacAddressData", // iOS pre-12.0
    "5pYKlGnYYBzGvAlIU8RjEQ", "HardwarePlatform", // iOS pre-12.0
    "5QM8apssQbhm2ZrUx5g5Tw", "pipelined-stillimage-capability", // iOS pre-12.0
    "5tnvmEsHQKfCoieLEYpnvg", "RFExposureSeparationDistance", // iOS pre-12.0
    "5v2p6i7PyIMdWOK4n/+G4A", "proximity-sensor", // iOS pre-12.0
    "5Y72WwdS5NYHdc00gEZ/DQ", "ExtendedLOMMacAddressData", // iOS 26.0-
    "5y8gwXr/HXkhryza4xQeFg", "DeviceSupportsMapsBlurredUI", // iOS pre-12.0
    "61xs1bQ+9eTk8tlRvG9UKw", "MicrophoneCount", // iOS pre-12.0
    "67A3BpQkCRe1ihx0Me4lgg", "arkit", // iOS pre-12.0
    "67Dsh4G8EGQp4WbPDfS/Xw", "YonkersSerialNumber", // iOS pre-12.0
    "67x5O+zO+JwnGgmKlq+qdA", "DiagData", // iOS pre-12.0
    "68eiAurB2LJ96Vz/CzaAcA", "DeviceSupportsMTP", // iOS 26.0-
    "6IejgN+1Fmu5/QrZFOIeNw", "DeviceSupportsPulseWidthMaximization", // iOS 26.0
    "6IFOueGt1uQWk1sz50VIVg", "WatchSupportsVoiceEditing", // iOS 26.0
    "6iI7/9cVUGIjdrSvIXEt4A", "RearCameraCapability", // iOS pre-12.0
    "6JkXMDhnrEMvLiRlYJL6zA", "RingerButtonNormalizedCGRect", // iOS 26.0-
    "6k70IxahfOQTZbGwu++QwA", "additional-text-tones", // iOS pre-12.0
    "6MnVtR+c9LeR46bMxvR5Yw", "RegionalBehaviorNoVOIP", // iOS pre-12.0
    "6pjDdEw65TFyL1FmIdszXw", "hd-video-capture", // iOS pre-12.0
    "6RrxXzvfw2GZeUPLKXxrmA", "RearFacingCamera60fpsVideoCaptureCapability", // iOS pre-12.0
    "6S9CvPHPtzHQqKudHSfsag", "haptics", // iOS pre-12.0
    "6UUmcaeT7rJoyUVmoPJd4A", "ProximitySensorCalibration", // iOS pre-12.0
    "6VRApe6L2vc1r2s+xts9/w", "DeviceSupportsIndependentOutputOnSpeaker", // iOS 26.0-
    "6WdGcQGw4VLzrgxJo+bcrw", "UniqueChipIDString", // iOS 26.0-
    "7AqG7ADB9UZgLLYKd9ZhrQ", "DeviceSupportsContextualVolume", // iOS 26.0
    "7D54DikSnFQnbDEBwlKQTQ", "DevicePrefersCheapTrafficShaders", // iOS pre-12.0
    "7DfjbzhvH/GDkhio1dv8fA", "HasSEP", // iOS pre-12.0
    "7IgVvZZLtNjMFdInQlKg6A", "SoftwareBehavior", // iOS pre-12.0
    "7l0BaQsNxJCanoeHMJ2huA", "AllowYouTube", // iOS pre-12.0
    "7mV26K/1a+wTtqiunvHMUQ", "PhosphorusCapability", // iOS pre-12.0
    "7UhDrmrZozgwO+3AgUbHxw", "DeviceSupportsSecureMicrophone", // iOS 26.0-
    "7VoVaBmSuokzovhUkiDx6Q", "SecondaryWifiMacAddress", // iOS pre-12.0
    "7W2eNk/f6uewC8N58mlRrQ", "FrontFacingCameraHDRCapability", // iOS pre-12.0
    "7yzVesPANxqKQ+oqNPhTwg", "applicationInstallation", // iOS pre-12.0
    "7ZipyD32hkjOUTl66Q8REw", "DeviceSupportsLockdown", // iOS 26.0-
    "8/HMvzDR3J6m0aY3NYeqcg", "bluetooth-le", // iOS pre-12.0
    "8/tysfSvORoyVg9IE901oQ", "DeviceRGBColor", // iOS pre-12.0
    "81Zj1535/jeXbmfOndlIVA", "youtubePlugin", // iOS pre-12.0
    "82Ono2SP03rNGkhOc5O1Mw", "DeviceRequiresPetalOptimization", // iOS pre-12.0
    "87sSAh2rboMI2TDvFBimkg", "DeviceColorMapPolicy", // iOS pre-12.0
    "8bCjks0zVuOcdivIhytNbQ", "lidar-scanner", // iOS 26.0-
    "8bOgXKgqoLvqV/XeSomAfA", "SecondaryBluetoothMacAddress", // iOS pre-12.0
    "8bY/L3i3rmxrl4ZjFZZpgQ", "siri-gesture", // iOS pre-12.0
    "8DHlxr5ECKhTSL3HmlZQGQ", "RestoreOSBuild", // iOS pre-12.0
    "8fyX2yEg28cYgJ10Yl+ueA", "QuickNoteCapability", // iOS 26.0-
    "8gVfz9/8R1OtWBBtI0o/+Q", "DeviceSupportsTimeInDaylight", // iOS 26.0-
    "8LAJHwc8DUQZwV2TSwsysA", "RearFacingCameraStageLightPortraitCaptureCapability", // iOS 26.0-
    "8olRm6C1xqr7AJGpLRnpSw", "PearlIDCapability", // iOS pre-12.0
    "8OTc3mN30ACaEwecgpKfXA", "CloudPhotoLibraryCapability", // iOS pre-12.0
    "8QNz35Yxm0KqxP1JiE0HIw", "PintoMacAddressData", // iOS pre-12.0
    "8S7ydMJ4DlCUF38/hI/fJA", "front-depth-camera", // iOS pre-12.0
    "8Shl+AdVKo09f1Sldkb0kA", "touch-id", // iOS pre-12.0
    "8Vbp0HyqndjWuIFZibhu7g", "DeviceSupportsGrey", // iOS 26.0-
    "9/J7LY7zuYSGW1BcSTRpOw", "SysCfgDict", // iOS pre-12.0
    "913P3Zsei09w0GSSOaBD+w", "VolumeUpButtonNormalizedCGRect", // iOS 26.0-
    "91LyMcx4z1w3SGVeqteMnA", "BasebandRegionSKU", // iOS pre-12.0
    "96GRvvjuBKkU4HzNsYcHPA", "MinimumSupportediTunesVersion", // iOS pre-12.0
    "97JDvERpVwO+GHtthIh7hA", "RegulatoryModelNumber", // iOS pre-12.0
    "9MZ5AdH43csAUajl/dU+IQ", "SupportedDeviceFamilies", // iOS pre-12.0
    "9n2qz3uDC5nSe1xZG1/Bkw", "CarrierInstallCapability", // iOS pre-12.0
    "9N7qIucqhr0Cy2/Tk27/hw", "DeviceCoverGlassColor", // iOS pre-12.0
    "9RryeqF6OCWlbaXP2Qsoag", "DeviceProximityCapability", // iOS 26.0-
    "9s45ldrCC1WF+7b6C4H2BA", "GSDeviceName", // iOS pre-12.0
    "9UCjT7Qfi4xLVvPAKIzTCQ", "ReleaseType", // iOS pre-12.0
    "9uRuEueUQZFyet0P69AWMw", "ExtendedSecurityDomain", // iOS 26.0-
    "9ZqSL68MJyQESzQFDvKqXA", "voip", // iOS pre-12.0
    "a/mex6YNO6gJ8N8SxAA71A", "DeviceSupportsCrudeProx", // iOS pre-12.0
    "a13V9f9x26JcQCfczZAVAw", "ui-traffic-cheap-shaders", // iOS pre-12.0
    "a1eUrgG+tlRzm4B5fqIdeg", "DeviceSupportsUltraLowPowerNetworking", // iOS 26.0
    "a1r7npIrhXsZ7SmKRKC1eA", "DeviceSupportsHDRPhotoDisplay", // iOS 26.0-
    "a4GiDGlLmW0qD340gOCpFA", "MacPrefsAssetImage", // iOS 26.0-
    "a5BRUxn1QBPXkAnbAHbmeg", "SigningFuse", // iOS pre-12.0
    "A62OafQ85EJAiiqKn4agtg", "DeviceSupportsGenerativeModelSystems", // iOS 26.0-
    "a6vjPkzcRjrsXmniFsm0dg", "ShouldHactivate", // iOS pre-12.0
    "aadL+4GFBDe6DdsUD2HGGw", "StoreDemoMode", // iOS 26.0-
    "aCQx2Qq/TChnNAq1rr6Egw", "DeviceSupportsAlwaysOnCompass", // iOS pre-12.0
    "aD51uqjUwgRKjAC04BCrxg", "VolumeUpButtonCGRect", // iOS 26.0-
    "aDuN0jCthN9lLu4qQ9OrEA", "CameraIMUDistanceType", // iOS 26.0-
    "AFXhxraF1bvyaCMlBIOZPA", "RequiredBatteryLevelForSoftwareUpdate", // iOS pre-12.0
    "AGrtXj3nqzz8KFfFHK7/sA", "ThreadRadioMacAddressForProvisioning", // iOS 26.0-
    "Aixt/MEN2O2B7f+8m4TxUA", "HasExtendedColorDisplay", // iOS pre-12.0
    "AJFQheZDyUbvI6RmBMT9Cg", "HasBaseband", // iOS pre-12.0
    "AklmqJyJMChzHsYT0aiBbw", "LaunchTimeLimitScaleSupported", // iOS pre-12.0
    "aoAKcHLuTUp/o3squcJkhA", "CompassCalibrationDictionary", // iOS pre-12.0
    "AOIh1l3cIyDXlP4KB/084A", "iap2-protocol-supported", // iOS pre-12.0
    "aoJSd/MXk7M40NgXTM6x+g", "DeviceSupportsAlwaysOnDisplayFlipbook", // iOS 26.0-
    "AoKnINTLPoKML3ctoP0AZg", "IOSurfaceFormatDictionary", // iOS pre-12.0
    "aOq/O8u9f/bpWUnKco+xgA", "EthernetMacAddressData", // iOS pre-12.0
    "APeknA55ZAcu0FcufqVN4Q", "FaceTimePreferredDecoding", // iOS pre-12.0
    "AQiIpW0UeYQKnhy2da7AXg", "EffectiveProductionStatusAp", // iOS pre-12.0
    "AspYltP/iGWg0qxfg7c/3w", "SupportsLEDAging", // iOS 26.0-
    "AthxlkPBk46HtzM9AxK9vg", "explicitContentRestriction", // iOS pre-12.0
    "AtmPEO/j+Pdr8+WKxv4Aaw", "DeviceEnclosureMaterial", // iOS pre-12.0
    "atOCpGf+lHCxgJ9GElef8Q", "SEInfo", // iOS pre-12.0
    "aVL5GE3tx0LSCI/ErfrJGA", "DeviceSupportsAudioMix", // iOS 26.0
    "AWEfP3xWh0q1MjO3JAy/AA", "CPUSubType", // iOS pre-12.0
    "awim/yUQvLyTrKsoKhg2bA", "DeviceSupportsELabel", // iOS pre-12.0
    "awLQ2KgwSTZswuKgSSjmEQ", "DisplayMaxNits", // iOS 26.0-
    "AX/UKxSHwm+OuFRIdvNAfg", "DeviceSupportsAutoLowLightVideo", // iOS pre-12.0
    "aYjxnADoQ2HXS8J+swzuNg", "DeviceSupportsDarwinInitConfigFromNVRAM", // iOS 26.2
    "b2BKAEe88VRfp2WXEjJOyA", "SIMStatus2", // iOS pre-12.0
    "b4e7mEbjqfewD6oXmo9U5g", "HWModelDescriptionForPowerPerf", // iOS 26.0
    "Bb01MNJ0ezfSmzucKZXrsg", "DynamicFunctionRowSerialNumber", // iOS 26.0-
    "bbtR9jQx50Fv5Af/affNtA", "PhysicalHardwareNameString", // iOS 26.0-
    "BdS2M69XMEc9v/jsHBC3Eg", "ThreadRadioCapability", // iOS 26.0-
    "Bg8VW4HdQj+GVY+191T3nQ", "DeviceSupportsSideButtonClickSpeed", // iOS 26.0-
    "bGUN8lS6sYzy3xhePubp8A", "KeyboardMutePreservesRegionalShutterClickBehavior", // iOS 26.0-
    "bhPjDx/0UDk9mzia6ksZ+A", "nike-support", // iOS pre-12.0
    "Bim3FC83Te8QX1kfSpqYKQ", "KeyboardMutePreservesRegionalShutterClickBehaviorForLegacyDevices", // iOS 26.0-
    "Birtx7GxrxCCUzsE1JQO8Q", "LowPowerWalletMode", // iOS pre-12.0
    "bl+nF6e86pLBiPP4pVJ24g", "PhotoCapability", // iOS pre-12.0
    "BoNz1QXiAEUgic9RdMVLIg", "FaceTimeEncodings", // iOS pre-12.0
    "BOPZue5C0v42pU9iJFYE3A", "location-reminders", // iOS pre-12.0
    "BOYfUi496moe56A0RWFbqQ", "sensitive-ui", // iOS pre-12.0
    "BQwz+BT9b5mS7OPh2WGD6A", "SecondaryEthernetMacAddress", // iOS pre-12.0
    "bt5D9RI67C9koJO1oZ5cfg", "EOSHalleyConfiguration", // iOS 26.0-
    "bUJD9zcOcitJwFA0ieIkxA", "DeviceBackGlassMaterial", // iOS pre-12.0
    "bwLsbkp4shhHuNB5VpRa8w", "YonkersUID", // iOS pre-12.0
    "BWoQXWXYITrPRpFyc9xTLw", "DeviceSupportsUSBTypeC", // iOS pre-12.0
    "byGRtH44VNik9CzN/QKLCw", "nfc", // iOS pre-12.0
    "bysMryc4yLwQjKvUQGGXXQ", "DevicePrefersProceduralAntiAliasing", // iOS pre-12.0
    "c5uqoV7Z9ly+f4c5mYXILg", "OfflineDictationCapability", // iOS pre-12.0
    "c7fCSBIbX1mFaRoKT5zTIw", "WifiVendor", // iOS pre-12.0
    "cBy4BcYs5YWtFHbBpt4C6A", "DeviceSupportsHaptics", // iOS pre-12.0
    "ce5pjDJVSOxjcg1HwmAezA", "opengles-2", // iOS pre-12.0
    "ceKgtkUE4F9ywcr57zdUWA", "DeviceSupportsAOP2", // iOS 26.0-
    "ChBMzkxYdT9Xmw3QN5kMWA", "DeviceSupportsSimplisticRoadMesh", // iOS pre-12.0
    "CJcvxERO5v/3IWjDFKZKRw", "DeviceBackingColor", // iOS pre-12.0
    "CK3I7fFGkgeqzKEhGew9rQ", "FaceTimeFrontCameraTemporalNoiseReductionMode", // iOS pre-12.0
    "cm399FbDqnv8IOFoeBLWYg", "RearFacingTelephotoCameraModuleSerialNumber", // iOS pre-12.0
    "CN/XFuy/9Fdv0yE+28kwRQ", "cell-broadcast", // iOS pre-12.0
    "CN64p1hw1JVdTHCfBdgPLQ", "BasebandStatus", // iOS pre-12.0
    "CnoPCMssOh+xPJJo6pvnog", "WatchSupportsAutoPlaylistPlayback", // iOS pre-12.0
    "CoWnN4xo783YGn4wLrUatA", "DeviceSupportsDisplayPort", // iOS 26.0-
    "CPiqZJJPocpjc5C5qe1tiw", "ArrowUniqueChipID", // iOS 26.0-
    "CpVSHukvtqlJzCgSdoHW5w", "SBAllowSensitiveUI", // iOS pre-12.0
    "CQ6gFmgMhpnnISvG6VakBQ", "MobileSubscriberCountryCode", // iOS pre-12.0
    "cRjPy4Ef+KZwJ+nfPeBV5Q", "DeviceSupportsSwimmingWorkouts", // iOS pre-12.0
    "cT44WE1EohiwRzhsZ8xEsw", "RingerButtonCapability", // iOS 26.0-
    "ct5Dh6u0D6WDJKg2PrMFVQ", "FaceTimePreferredEncoding", // iOS pre-12.0
    "cux58RcuSiBhpxWnT3pE4A", "FrontFacingCameraVideoCapture4kMaxFPS", // iOS pre-12.0
    "cVdYn5ajyDgnkT7YmtD1Gg", "RunnableArchitectures", // iOS 26.0
    "cW+7coMzO/hTtCCDcSvNOw", "RequiresNaturalVolumeButtonArrangement", // iOS 26.0-
    "CwvKxM2cEogD3p+HYgaW0Q", "CameraButtonCapability", // iOS 26.0-
    "cWWKdUn+rIclZ60ZGAVhBw", "CameraHDR2Capability", // iOS pre-12.0
    "cX1+ZsVacGTXWVKB9enYow", "shoebox", // iOS pre-12.0
    "cZflGJ39lJHTCPy35/N14Q", "SiliconBringupBoard", // iOS pre-12.0
    "CzGP5+8jQECJMH4h+z4TYA", "offline-dictation", // iOS pre-12.0
    "D0cJ8r7U5zve6uA6QbOiLA", "ModelNumber", // iOS pre-12.0
    "d27R2IjPvpwp+MX/kUbJ2w", "PintoMacAddress", // iOS pre-12.0
    "D4AU4tOIuGKN3G/uix65cQ", "RegionalBehaviorAll", // iOS pre-12.0
    "D6/BMDrlb8V3WSiqL8gL+w", "DeviceSupportsBatteryModuleAuthentication", // iOS pre-12.0
    "DcQNvnO5Uhpc1jjGIrzyng", "BatterySerialNumber", // iOS pre-12.0
    "DdNpmCCXbeMGbqj0kAMCdw", "piezo-clicker", // iOS pre-12.0
    "DGBWzPMdVuqPxgH7iSz3SA", "3Gvenice", // iOS pre-12.0
    "dI30ovtFUIeLioNQKDMbGQ", "DeviceSupportsConcurrentHPLPMics", // iOS 26.0-
    "diS7AlmwFZz6NyF7CY97sA", "CoastlineGlowRenderingCapability", // iOS pre-12.0
    "Djv9tHz6MLdTUDjnkq0obQ", "BasebandFirmwareUpdateInfo", // iOS pre-12.0
    "dJvRNnysMoubdy0ZCK2aRQ", "JasperSerialNumber", // iOS 26.0-
    "DoMjIR2qPkxXtP/kDu/gfQ", "DeviceSupportsSecureDoubleClick", // iOS 26.0-
    "dp7SlZZQotrh8McQoH1xFA", "rear-facing-camera", // iOS pre-12.0
    "dQf5OObttLFgJniqrS19qA", "FrontCameraRotationForISP", // iOS 26.0-
    "drMm12aFyD64om7eXVFRVA", "DeviceSupportsDynamicEndOfCharge", // iOS 26.0-
    "DrrXMX9VWX7bMj0MZuhTUA", "DeviceKeyboardCalibration", // iOS 26.0-
    "DrSqlXYNVfYXCvAsuUrUDA", "DebugBoardRevision", // iOS pre-12.0
    "DtSpvgyOyNVwNa5W0zigqg", "DeviceSupportsMomentCapture", // iOS 26.0-
    "DViRIxZ/ZwO007CLcEYvZw", "SoftwareBundleVersion", // iOS pre-12.0
    "dW5fpt/6HhaTbnK/UqL6cA", "HWModelDescriptionForAudio", // iOS 26.0
    "DWrhyh1BwYypYmW5q78Wuw", "armv7", // iOS pre-12.0
    "DxmNcovWWN464hwZdGfonA", "CameraButtonNormalizedCGRect", // iOS 26.0-
    "dz7F2FFseAysXoUZqaANZw", "DeviceSupportsEUCapabilities", // iOS 26.0-
    "DzLC4o1jZ4hWtP8aB6An6g", "SDIOManufacturerTuple", // iOS pre-12.0
    "E+9+cggZ2rXU0z8mWiOung", "AllowPhoneApp", // iOS 26.2
    "e0HV2blYUDBk/MsMEQACNA", "DeviceSupportsBreathingDisturbancesMeasurements", // iOS 26.0-
    "E0wrprlNya8gngoVpPXj2w", "DeviceSupportsCorrectedTemperature", // iOS 26.0-
    "E4vGMChwcVRKD8hMVxnRvg", "DeviceSupportsUSLegallyCompliantBloodOxygen", // iOS 26.0
    "e4ZSDal1Fg7QfCA7rlNmSQ", "DeviceSupportsLiveActivities", // iOS 26.0-
    "e8KVLQDfW5n4LxdE3N84Xw", "DeviceSupportsCyclingAutoStartReminders", // iOS 26.0-
    "E9a3UzlfYjWEB9viQCHNAA", "DeviceSupportsCameraDeferredProcessing", // iOS 26.0-
    "Eavu9TP+iZ0Lzlk7FU6w6Q", "ActiveWirelessTechnology", // iOS pre-12.0
    "ebyBs0j3KAquBsgcfrNZIg", "CellularTelephonyCapability", // iOS pre-12.0
    "ee9YfVjjsbVte45bYSt4Wg", "DeviceSupportsNavigation", // iOS pre-12.0
    "eg8KDO//lXaLwp+URGP6DA", "CertificateSecurityMode", // iOS pre-12.0
    "eH9J8yYIjbRNxg2EeYvNFg", "UIBackgroundQuality", // iOS pre-12.0
    "EImfMz+bzJrUkVQKyY6tEg", "BasebandSecurityInfoBlob", // iOS pre-12.0
    "eJGhnVvylF3dMOHBKJzeiw", "AppleNeuralEngineSubtype", // iOS 26.0-
    "eLfYx8jpSlim2NZFIonPzA", "WifiCallingSecondaryDeviceCapability", // iOS pre-12.0
    "ELLSWiPOyh0roYBypZFHFA", "magnetometer", // iOS pre-12.0
    "emXA9B552rnSoI7xXE91DA", "DeviceLaunchTimeLimitScale", // iOS pre-12.0
    "eNgz35a7iZnVeEMwsBQZew", "BasebandChipId", // iOS pre-12.0
    "eP/CPXY0Q1CoIqAWn/J97g", "DeviceSupportsLandscapeFaceID", // iOS 26.0-
    "eQd5mlz0BN0amTp/2ccMoA", "SupportsForceTouch", // iOS pre-12.0
    "EqrsVvjcYDdxHBiQmGhAWw", "apple-internal-install", // iOS pre-12.0
    "ErupMbaQrM6KypD4K0kTDQ", "OpenGLESVersion", // iOS pre-12.0
    "eu8pUYR7yo+AlS9aojlgwg", "DeviceSupports4G", // iOS pre-12.0
    "euampscYbKXqj/bSaHD0QA", "IsPwrOpposedVol", // iOS pre-12.0
    "EuwCLwMXh+X5LErHKwvuIw", "MultiTouchMaxBootTime", // iOS 26.0-
    "evtY5EeJ8V0nFhmrj/OYjg", "NFCUniqueChipID", // iOS pre-12.0
    "eW5H/Gwg0uqbMqFot70pYg", "PerfLevelCapability", // iOS 26.0-
    "Ex6ChutQnIx5Zm6c5uwYuw", "AllowOnlyATVCPSDKApps", // iOS pre-12.0
    "eXCYx/SHTZIn5LInWvZByw", "call-waiting", // iOS pre-12.0
    "ExSUJyf7MblY5nBQx2OaRw", "ScreenRecorderCapability", // iOS pre-12.0
    "eXzS2kvF8nNOI/xIJKquHg", "DeviceSupportsScandium", // iOS 26.0-
    "eZS2J+wspyGxqNYZeZ/sbA", "WifiAddressData", // iOS pre-12.0
    "f+PE44W6AO2UENJk3p2s5A", "SupportsLowPowerMode", // iOS pre-12.0
    "F1Xz9g1JORibBS9DYPUPrg", "BlueLightReductionSupported", // iOS pre-12.0
    "f2DlVMUVcV+MeWs/g2ku+g", "BatteryCurrentCapacity", // iOS pre-12.0
    "f8peylp799CJta4Ev/vz8A", "hiccough-interval", // iOS pre-12.0
    "fbpzGGoBNcvDLt4LlZGnfA", "DeviceSupportsSingleDisplayEnhancedMultitasking", // iOS 26.0-
    "FBw/2WrPE2supEKosxxoTw", "WatchAppButtonCapability", // iOS 26.0-
    "fdh+s6j3VijuyrK7xLjd7g", "main-screen-class", // iOS pre-12.0
    "FDsm68UVR7l3wErusGLgKg", "hw-snapshots-need-purplegfx", // iOS pre-12.0
    "FE4Tff1EICGXaI27X3P/dw", "web-browser-engine", // iOS 26.0-
    "Fe55gxpfp6SByfqjASqF5A", "embedded-web-browser-engine", // iOS 26.0-
    "feC7TgoAAKLjn/KU8JAKFA", "DeviceSupportsExternalHDR", // iOS 26.0-
    "fGpT09KNGDBjFXnqcVbgbw", "RearFacingCameraHFRCapability", // iOS pre-12.0
    "Fh2Ga0/Sj4T3Qn5Z9A9BMw", "DeviceSupports4k", // iOS pre-12.0
    "fh6DnnDGDVZ5kZ9nYn/GrQ", "hdr-image-capture", // iOS pre-12.0
    "Fhqq6Bhy/XnCEBRAe3TI+g", "SavageInfo", // iOS pre-12.0
    "fI93k3j19qMaEqYkKKI7BQ", "FrontFacingCameraSuperWideCameraCapability", // iOS 26.0-
    "fJZs6N8SqTS4RuQVh3szxA", "camera-front-flash", // iOS pre-12.0
    "FkD7K642S082lnfw/ohHzg", "BasebandFirmwareManifestData", // iOS pre-12.0
    "fkWvcjYnYzGRhVKiBoYzgA", "HasPKA", // iOS pre-12.0
    "FLmEtGw+OD98VLXasx7W6A", "DeviceSupportsWirelessChargingEnergyUseNotification", // iOS 26.0-
    "FNvQ6lBvJIUcYBzQ8ggOUQ", "SavageUID", // iOS pre-12.0
    "FOs+LbLUs+TajsEE4xkbrw", "gas-gauge-battery", // iOS pre-12.0
    "fqNtLlgbYfa9gSNrhg7VGQ", "encode-aac", // iOS pre-12.0
    "frZQaeyWLUvLjeuEK43hmg", "InverseDeviceID", // iOS pre-12.0
    "FtgLNPlv55lerm7FY/kClw", "AbsoluteDepthLimit", // iOS 26.0-
    "fu+4kyf8VcMBtgbMyJlLtg", "WorkoutUltraMode", // iOS 26.0-
    "fucd7llSuoCNHrrvLS1QQg", "watch-companion", // iOS pre-12.0
    "fuKL2rMywRgQF1wowOA/cg", "DeviceBrand", // iOS pre-12.0
    "fv8ZXM/NhUHQBQqCSk19cA", "FrontFacingCameraAutoHDRCapability", // iOS pre-12.0
    "fW9C1U4C1FR8bwe1VqEWug", "full-6", // iOS pre-12.0
    "FymLPtOEy6FdE7TmKeoTdg", "DeviceSupportsSingleCameraPortrait", // iOS pre-12.0
    "fYsrGTmVTbneEs3HKetEdQ", "FrontFacingCameraSingleCameraPortrait", // iOS 26.0-
    "g+9NpjmSVwtomd8nyNJimg", "armv6", // iOS pre-12.0
    "g/MkWm2Ac6+TLNBgtBGxsg", "HEVCEncodingCapability", // iOS pre-12.0
    "g5LBi+DCiP5+jUnWVL7Y9w", "FrontCameraRotationFromDisplayNormal", // iOS pre-12.0
    "g7vU4YF+9Z+wkSvw/Cm8Dg", "CoreRoutineCapability", // iOS pre-12.0
    "g7YQ1Djxh4YiKlEeaoGhzg", "main-screen-width", // iOS pre-12.0
    "G91h5IuJvXISeyngNFqEpg", "ProductTypeDescForUserVisibility", // iOS 26.0
    "gB6cQZBLeMojsPAaE/iRtg", "SpatialAudioProfileCapability", // iOS 26.0-
    "gBw7IWiBnLHaA+lBrZBgWw", "CameraMaxBurstLength", // iOS pre-12.0
    "gD8SNRcHQeIxCAvsp+2vjA", "WSKU", // iOS pre-12.0
    "GdXjx1ixZYvN9Gg8iSf68A", "SupportsPerseus", // iOS pre-12.0
    "GEsznZwAYGOa1a67QU1Uew", "ProductTypeDescForPowerPerf", // iOS 26.0
    "GGIIDN/ANr8X2WrgS6nBYQ", "HWModelUniqueStr", // iOS 26.0
    "ghpAuGJlPoauWijdtPi7sQ", "UserAssignedDeviceName", // iOS pre-12.0
    "gI6iODv8MZuiP0IA+efJCw", "WifiAddress", // iOS pre-12.0
    "gizLvTWx1sMUYQ9EYr/N4g", "CountryOfOrigin", // iOS 26.0-
    "gKzNJcweSCWA+gIGiUQJ5w", "mms", // iOS pre-12.0
    "gLd6IDfbVM+JiOhktEP7Bw", "SupplementalBuildVersion", // iOS 26.0-
    "Glo+aTkt0Uw31BghCxnsyQ", "BridgeRestoreVersion", // iOS pre-12.0
    "gme55xrmjlSlBkahnZq36A", "MetalPerfLevelCapability", // iOS 26.0-
    "gnQwi8RnEeMG9qBe3IUKrg", "DeviceCoverGlassMaterial", // iOS pre-12.0
    "GO5/TJivIXtQkTkFWkRc9A", "certificate-production-status", // iOS pre-12.0
    "GPIs61LYNpcwZqwlFr7bbg", "DeviceSupportsCompassOrienteering", // iOS 26.0-
    "gPoIZFd4NhmSKrk67qH80w", "SBCanForceDebuggingInfo", // iOS pre-12.0
    "gq0j1GmcIcaD4DjJoo9pfg", "RearFacingCameraStillDurationForBurst", // iOS pre-12.0
    "GqAdWRLnC7oYQrNYF48VYA", "SubProductType", // iOS 26.0
    "gqDnklGQnpv5ilgh5uHckw", "DeviceSupportsClosedLoopHaptics", // iOS pre-12.0
    "gQDt76Te0SPw7N8oTLrBFw", "DeviceSupportsCameraCaptureOnTouchDown", // iOS pre-12.0
    "grEfqkFsEkgnJH1nl9sodw", "effective-production-status-sep", // iOS pre-12.0
    "guykxGaRwHdenUK8fJRl8w", "gamekit", // iOS pre-12.0
    "GxXmRWHjsY5yAVhMfCH6Lg", "BridgeBuild", // iOS pre-12.0
    "H+r3Nk8ByXIY9ub/M8broA", "DeviceSupportsHeartHealthAlerts", // iOS pre-12.0
    "h1UG2n5HnANzU4rX8pT85g", "DeviceDBVDependentVSHCompensationTraits", // iOS 26.0
    "H5HW20mJr/djc40tAehkww", "BasebandKeyHashInformation", // iOS pre-12.0
    "H5TSt7Pu4zNCD5RvHuk5CQ", "PhoneNumber", // iOS pre-12.0
    "h63QSdBCiT/z0WU6rdQv6Q", "RegionCode", // iOS pre-12.0
    "H8Pi7AthQFVZ0B6A1J5OTw", "photo-adjustments", // iOS pre-12.0
    "h8xonkkn/NzDMvvCXLw8cQ", "FaceTimeBitRateWiFi", // iOS pre-12.0
    "H97G3GzDYb4wY5kwJ0AKfQ", "ForwardCameraCapability", // iOS pre-12.0
    "h9jDsbgj7xIVeIQ8S3/X3Q", "ProductType", // iOS pre-12.0
    "HBf5L3fT108kze+YWeiy+w", "VSHCompensationMinimumNits", // iOS 26.0-
    "HCzWusHQwZDea6nNhaKndw", "DeviceSupportsCollisionSOS", // iOS 26.0-
    "heP+NTlvkhJ2zzWIUznawA", "MobileEquipmentInfoBaseProfile", // iOS pre-12.0
    "hewg+QX1h57eGJGphdCong", "DeviceSupportsPortraitLightEffectFilters", // iOS pre-12.0
    "hfs43coKE3iWlCwnqPgBpg", "IceFallID", // iOS pre-12.0
    "HHF6YgqEQ9Kd7MBSVnLsgg", "DeviceSupportsAOP", // iOS pre-12.0
    "hhRNi2d3z2WEFmU+xG/EXw", "ActuatorResonantFrequency", // iOS pre-12.0
    "HIaq6xVZ/V8B9pnigcvqCA", "DeviceSupports3DMaps", // iOS pre-12.0
    "hiHut/WR+B9Lx/vd0WyeNg", "wapi", // iOS pre-12.0
    "HkXhfA7q9eBKIU2+6yTgQg", "screen-dimensions", // iOS pre-12.0
    "hLzlRnTuKAcQLWtNwCFSfg", "nfcWithRadio", // iOS pre-12.0
    "HMKkoKYsMmBBSN6ozOtw/w", "stand-alone-contacts", // iOS pre-12.0
    "HMpTbnbcAb+mQDi8O71h6Q", "LynxPublicKey", // iOS pre-12.0
    "HnHX0gXt8RvhMQzIVMM7hw", "FrontFacingCameraHDROnCapability", // iOS pre-12.0
    "hnXJ1OpiiIL0+p3jUG/XxQ", "RearFacingCameraSuperWideCameraCapability", // iOS 26.0-
    "hOkus/A6lBEF6Ar3jV7LrQ", "DeviceSupportsRGB10", // iOS pre-12.0
    "hpHV3xXxvU4XYjxfVgQLAg", "DeviceDisablesAODByDefault", // iOS 26.0
    "Ht1HDxwTOy2gyY+THjbd6w", "peer-peer", // iOS pre-12.0
    "HV7WDiidgMf7lwAu++Lk5w", "HasMesa", // iOS pre-12.0
    "hwd9ipb6eezNleN59+6n1Q", "metal", // iOS pre-12.0
    "hx2qJfJRLZ9Sseb37IcQow", "ringer-switch", // iOS pre-12.0
    "HXTqT3UXOKuTEklxz+wMAA", "BasebandAPTimeSync", // iOS pre-12.0
    "HxTvMvHnum5rI8d0Nr4xBw", "RegionalBehaviorVolumeLimit", // iOS pre-12.0
    "hykQtM0zkNe2/IY69+3PPQ", "ApNonce", // iOS pre-12.0
    "HzddeW2/HtdBNAc5tsFtDg", "SecondaryBluetoothMacAddressData", // iOS pre-12.0
    "I32sGclpgl5VujQRJxyhKQ", "IsUIBuild", // iOS pre-12.0
    "I3lidq+FVH2CeOi/ARa0tg", "generative-model-systems", // iOS 26.0-
    "I4TfkcdXWazwTr1al8Ml5w", "StrictWakeKeyboardCases", // iOS pre-12.0
    "i8+iwUtLtB5jT+WNvqwrEA", "encrypted-data-partition", // iOS pre-12.0
    "iaegRQa4jNGOuTA6hnZmcQ", "DeviceCoverMaterial", // iOS pre-12.0
    "IAJzgzhEVk3SMNuEhChs2w", "RemoteBluetoothAddressData", // iOS pre-12.0
    "ibhfX8FQ6b809N632Ey98g", "Allow32BitApps", // iOS pre-12.0
    "iBLsDETxB4ATmspGucaJyg", "IsLargeFormatPhone", // iOS pre-12.0
    "IBqcPacFMPIX8HMWob444A", "AirDropCapability", // iOS pre-12.0
    "IFBSPGnQVFrGFW+ujtZu6Q", "RegionalBehaviorNTSC", // iOS pre-12.0
    "iFOX66VmcijipO3YRc+AXg", "display-mirroring", // iOS pre-12.0
    "IGYvMgBnOsdJjgmSh7Pe1A", "SEPNonce", // iOS pre-12.0
    "IhNb6V2L1pt+hBlZMsm5FQ", "DeviceSupportsDCP", // iOS 26.0-
    "IIYjwu1lbAyGz5t0c4ECoA", "MainDisplayRotation", // iOS pre-12.0
    "iJAKoV0Bp88r37qG+kkXzw", "DeviceMemorySize", // iOS 26.0-
    "Ijs+pw5tRyxqSy5kfgZNuQ", "DeviceSupportsAbsoluteDepth", // iOS 26.0-
    "ik8OQ5JoYhyK8AoTx29MuA", "DeviceSupportsOnDemandPhotoAnalysis", // iOS pre-12.0
    "il2TbGC66RCTKaEgSOVlgQ", "DeviceSupportsMultiUser", // iOS 26.0-
    "ILaGO+KV5JAOq7Q5GEwbWQ", "AvailableDisplayZoomSizes", // iOS pre-12.0
    "IMLaTlxS7ITtwfbRfPYWuA", "DeviceVariantGuess", // iOS pre-12.0
    "IMUksyctl4kC/BFI2K/Qyw", "DeviceSupportsStageLightPortraitPreview", // iOS 26.0-
    "IMZVdlDQXGM67ILcDE7hlA", "HasHighBandwidthRadio", // iOS 26.0-
    "inECTnNyR97XWxm7jU8uqA", "MobileEquipmentInfoBaseId", // iOS pre-12.0
    "inLiSl5OQHJ1stAIvKH8wg", "RegionalBehaviorGB18030", // iOS pre-12.0
    "iTvGxmtSOnHv548XON379A", "DeviceMesaType", // iOS 26.0-
    "ivIu8YTDnBSrYv/SN4G8Ag", "ProductName", // iOS pre-12.0
    "IweaHIDpz+rknAcb3+xg9g", "AggregateDeviceVideoZoomFactor", // iOS pre-12.0
    "iyfxmLogGVIaH7aEgqwcIA", "green-tea", // iOS pre-12.0
    "izFv/qj3IUhqAIiEuYH6xw", "MusicStore", // iOS pre-12.0
    "j1pdCAYnpIEYMqIAitm3JA", "DeviceSupportsCinnamon", // iOS pre-12.0
    "J1QHVh74Nnd6Rqyiq71/yw", "AVDDecodingRate", // iOS 26.0-
    "j39y4QUrP6cvZY8Pjyv64w", "PearlMotionDetectionCapability", // iOS 26.0-
    "j4dedPnpeXouudM1+j3dsQ", "IntegratedCircuitCardIdentifier", // iOS pre-12.0
    "j8/Omm6s1lsmTDFsXjsBfA", "DeviceSupportsAlwaysOnTime", // iOS 26.0-
    "J912s3mVzhReVtPv4HwqNQ", "FaceTimeCameraRequiresFastSwitchOptions", // iOS pre-12.0
    "j9Th5smJpdztHwc+i39zIg", "MarketingProductName", // iOS pre-12.0
    "jaJWtlotaa+Y41lCs7NVHg", "RearFacingLowLightCameraCapability", // iOS 26.0-
    "jBGZJ71pRJrqD8VZ6Tk2VQ", "RearFacingCameraVideoCapture1080pMaxFPS", // iOS pre-12.0
    "jdLgKT+0BZmGrzd9J0cuPA", "camera-flash", // iOS pre-12.0
    "jgE7MmmkZAG0BiWVqD7bMQ", "BatteryIsFullyCharged", // iOS pre-12.0
    "JhEU414EIaDvAz8ki5DSqw", "DeviceEnclosureColor", // iOS pre-12.0
    "JHXk7RXOxvlqK+SxkwcM2A", "LowPowerExpressModesSupported", // iOS 26.0-
    "ji56BO1mUeT7Qg9RO7Er9w", "DeviceSupportsASTC", // iOS pre-12.0
    "jJ+5tnncQBcHo5T26MI5jA", "debug-board-revision", // iOS pre-12.0
    "jKFTzVOYcfTfNBh+yDrprw", "RearFacingCameraHFRVideoCapture1080pMaxFPS", // iOS pre-12.0
    "jkr5aFPOh/d6zTzNKYthBw", "DualSIMActivationPolicyCapable", // iOS pre-12.0
    "JkZlE8z9YwHjE1hnbMhcgA", "DeviceSupportsHDRDeferredProcessing", // iOS 26.0-
    "JLP/IinyzetEPztvoNUNKg", "AggregateDevicePhotoZoomFactor", // iOS pre-12.0
    "jMiqevikb6QWeHOhvLsw6A", "RenderWideGamutImagesAtDisplayTime", // iOS pre-12.0
    "Jq+xaurJgFzSwxOfTqtBGw", "SupportsSSHBButtonType", // iOS pre-12.0
    "Js8HVdVGRs8m5v94pMjkRw", "enforce-googlemail", // iOS pre-12.0
    "jSDzacs4RYWnWxn142UBLQ", "BluetoothAddressData", // iOS pre-12.0
    "juE6wCsjVG4bfAhgHcUVcQ", "MultiLynxSerialNumberArray", // iOS 26.0-
    "JUWcn+5Ss0nvr5w/jk4WEg", "device-name", // iOS pre-12.0
    "jWdMTTxiAZc+KNO6Bz2jNg", "MesaSerialNumber", // iOS pre-12.0
    "JWjvsupiqWYtIGwr8yGd8w", "ios-perf-level-2", // iOS 26.0-
    "JwLB44/jEB8aFDpXQ16Tuw", "HomeButtonType", // iOS pre-12.0
    "JXmZWYUbLoumvz7hu/GL0A", "FaceTimeBackCameraTemporalNoiseReductionMode", // iOS pre-12.0
    "jxx29Cq5bGHDnkcha4y/Rw", "SpeakerCalibrationMiGa", // iOS pre-12.0
    "k+KTni1jrwErpcDMEnn3aw", "MobileDeviceMinimumVersion", // iOS pre-12.0
    "K/R1GfGfCkXvEhaPS2Vrng", "DeviceSupportsSiriUnderstandingOnDevice", // iOS 26.0-
    "K57p2Tit1BlJ8rFbLl/Nqg", "DeviceSupportseARC", // iOS 26.0-
    "k5lVWbXuiZHLA17KGiVUAA", "BluetoothAddress", // iOS pre-12.0
    "k7QIBwZJJOVw+Sej/8h8VA", "CPUArchitecture", // iOS pre-12.0
    "Kao6GNYdAy5hwXblxeGYJQ", "DeviceSupportsBatteryInformation", // iOS 26.0-
    "KGlZoljMyZQSxfhROj0IFg", "data-plan", // iOS pre-12.0
    "khE304sL66yzf7K+2e+0cw", "DeviceSupportsUSBTypeCDisplay", // iOS 26.0-
    "kj5Hw7ZKY+hm7ZCs0Caznw", "ScreenCaptureWidth", // iOS 26.0-
    "kjKnJNt7HY90iN6rpbSeFQ", "RegionalBehaviorNoWiFi", // iOS pre-12.0
    "kKgJsWN/rBUAkimOtm/wbA", "arm64", // iOS pre-12.0
    "kkSkHTEei96N1ZehicOgoA", "AppCapacityTVOS", // iOS pre-12.0
    "KMgjmT+dsqBCXu1YQEcOFg", "RegionalBehaviorValid", // iOS pre-12.0
    "Knrkxkj5zZTf/FrPNQClgg", "GroundhogEnabled", // iOS 26.0-
    "Kq9K9xqDoUiUP7JEfg+pNw", "DeviceSupportsDoNotDisturbWhileDriving", // iOS pre-12.0
    "kt7gXeIiU0dLEKrgUSsLVw", "opengles-1", // iOS pre-12.0
    "kT9JwUR2xPCTHTdgvG3UdA", "torpedo", // iOS 26.0-
    "kWVFqaGBc3nOGmfM+ZpoEg", "tv-out-settings", // iOS pre-12.0
    "KXUnLpPZ6IZSE+As45CkhA", "SoftwareDimmingAlpha", // iOS pre-12.0
    "kyszW/uUGJFTVNQwFaf6og", "DeviceSupportsEnhancedAC3", // iOS pre-12.0
    "kyxFFGn+VS4L9a/bsvm19Q", "Image4Supported", // iOS pre-12.0
    "KzUQgIyBRinkweVMNUCOWA", "ArcModuleSerialNumber", // iOS pre-12.0
    "L+KOzmOzO5DiJUZl21QGVg", "StarkCapability", // iOS pre-12.0
    "l/bXsek3q5yjYDwoPAktVQ", "DeviceSupportsAlwaysAPVoiceTrigger", // iOS 26.0-
    "l/n0Z7pMB8k0GyTKz3v3Tw", "AirplaneMode", // iOS pre-12.0
    "l1CWke97nbaAcWDqA6T5LA", "DeviceSupportsElton", // iOS 26.0-
    "L2Oq7vNNUKuv+iJ4m9xtiw", "SIMTrayStatus", // iOS pre-12.0
    "l3rf7ZBrcaYn5mY5o7xiIg", "HardwareSupportsSecureDoubleClick", // iOS 26.0-
    "L47fh6KehOmR+AseqK2Xsw", "DeviceSupportsCCK", // iOS pre-12.0
    "L5al7b+7JATD/izSJeH0aQ", "cellular-data", // iOS pre-12.0
    "L8CqbJeM+rf7l7NSOjnAHg", "DeviceSupportsPortraitIntensityAdjustments", // iOS 26.0-
    "l8Xo/NV8/U585G1uBtW29w", "PressDemoMode", // iOS 26.0-
    "LAB8o3Bxs3CgNuzDawjRdw", "opengles-3", // iOS pre-12.0
    "lAu7Xt7uV5eHu3pIdfHyYA", "DeviceSupportsAlmond", // iOS 26.0-
    "LBJfwOEzExRxzlAnSuI7eg", "InternalBuild", // iOS pre-12.0
    "LBu9btCCMXARNP26vsImMw", "UnifiedGamingPerfLevelMacTier2", // iOS 26.0
    "Lcu6Zck+C/+AMO8qULacDw", "DeviceSupportsToneMapping", // iOS pre-12.0
    "LcUv5nw5flxnHlxWu9sJvw", "NavajoFusingState", // iOS pre-12.0
    "LE2kQ7U1iM32AmlhYvlagg", "SavageSerialNumber", // iOS pre-12.0
    "LeSRsiLoJCMhjn6nd6GWbQ", "FirmwareVersion", // iOS pre-12.0
    "Leuy56dCZmAMYoVCQGTfPA", "DeviceSupportsPeriodicALSUpdates", // iOS pre-12.0
    "Lg1EJX11Jb7EbveB6+YgVQ", "720p", // iOS pre-12.0
    "lHMDJnC58naUz2rOCJyVIw", "IntegratedCircuitCardIdentifier2", // iOS pre-12.0
    "li+w2foswFu0srn5UxdOug", "arm64e", // iOS 26.0-
    "LJ8aZhTg8lXUeVxHzT+hMw", "TimeSyncCapability", // iOS pre-12.0
    "LkWb+FyA1+ef2UD1Fx+kAw", "RearFacingCameraHDROnCapability", // iOS pre-12.0
    "lMkwc9AKT0h2rR0JfJJCqQ", "ChipConfigRack", // iOS 26.0
    "lo3szoQ4sLy7o3+ZD0GcAQ", "ambient-light-sensor", // iOS pre-12.0
    "lSpe1QHIya0aeNrjLTtaJA", "hidpi", // iOS pre-12.0
    "LTI8wHvEYKy8zR1IXBW1uQ", "ArtworkTraitDisplayGamut", // iOS 26.0-
    "lU5WxNTusw4lrrBSEBiZeQ", "ThreadRadioMacAddressForProvisioningData", // iOS 26.0-
    "LUy+wqFiBmou5hwM5OWbmA", "OceanComputeCarrierSlot", // iOS 26.0-
    "LvCIFE6lOM10QDqIEyYWRA", "PeekUICapability", // iOS pre-12.0
    "lwHRTZNO5Jq87pVlzdNGIA", "DeviceSupports720p", // iOS pre-12.0
    "m+FD6mX8VZzP95hOhM+jow", "hw-encode-snapshots", // iOS pre-12.0
    "M+WPVivF4iTnm1CC8c6h+A", "DeviceAlwaysPrewarmActuator", // iOS pre-12.0
    "M1n2sAqf33NAOgZRGxQYBA", "DeviceSupportsPersonalTranslator", // iOS 26.0
    "m4alZgBFhxNuTZyrEM2nbA", "MacFormFactor", // iOS 26.0-
    "m4UsCAgXhbdnwLebiyKMiw", "UIReachability", // iOS pre-12.0
    "m7lDS+oP8q0pGg+CO7RvPg", "DisplayBootRotation", // iOS 26.0-
    "m9ORTKMgu9A+zF+A61Zz5A", "DeviceSupportsPhotosLocalLight", // iOS pre-12.0
    "m9OWD0Y4Br0TZHUl6rGcOg", "SavageChipID", // iOS pre-12.0
    "mAAbkChrX3bpxPIffHG1BQ", "front-facing-camera", // iOS pre-12.0
    "meicxSe0OZJaae1hEiOV5Q", "SpeakerCalibrationSpGa", // iOS pre-12.0
    "meLhyIpGgxiQoFZD/OGPcQ", "CompassType", // iOS pre-12.0
    "mG0AnH/Vy1veoqoLRAIgTA", "MedusaFloatingLiveAppCapability", // iOS pre-12.0
    "Mgwtle8wzQEz/0vzBk47FQ", "DeviceSupportsLineIn", // iOS pre-12.0
    "Mh+drGtyBfLYKN02sROzxg", "delay-sleep-for-headset-click", // iOS pre-12.0
    "Mi/ME+v1wZqkvXFU3xX3KA", "iphone-ipad-minimum-performance-a12", // iOS 26.0-
    "MjqwTHDneTCNeqhZ7vCvUw", "DeviceSupportsHiResBuildings", // iOS pre-12.0
    "Mk4ZslaChmO+6s3h7L1w6Q", "DeviceSupports1080p", // iOS pre-12.0
    "MKE8hwsOxxRCtwBk2aDBZA", "ProductTypeDescForAutomatedTesting", // iOS 26.0
    "mL1lk3ZVGDFUQhxU9YLW6Q", "FrontFacingCameraHFRVideoCapture1080pMaxFPS", // iOS 26.0-
    "mmu76v66k1dAtghToInT8g", "UIParallaxCapability", // iOS pre-12.0
    "MQJ1mlVrhOwaUUVJehJSVA", "WatchKeyboardCapability", // iOS 26.0-
    "MrC93gcyPVLHmEbzUu9uzQ", "IsVirtualDevice", // iOS 26.0-
    "MTa8c+pEdbK0tHGXP06xOw", "AllowYouTubePlugin", // iOS pre-12.0
    "mtHZd1H8XJ2DMVtNVUSkag", "wifi", // iOS pre-12.0
    "mtrAoWJ3gsq+I90ZnQ0vQw", "DeviceClassNumber", // iOS pre-12.0
    "mumHZHMLEfAuTkkd28fHlQ", "DeviceColor", // iOS pre-12.0
    "mVenV0u+B3ShrqRddinaFQ", "homescreen-wallpaper", // iOS pre-12.0
    "MW1p1oJH8nDJc6igOb8G4g", "IcefallInfo", // iOS pre-12.0
    "MWduuAGptrl7qIzWqBmOqQ", "AWDID", // iOS pre-12.0
    "MWpHV1VYKXmaKqhgbmTWCg", "ptp-large-files", // iOS pre-12.0
    "mx9l9PlJACEcOixUVDZEjg", "EphemeralDataModeOverride", // iOS 26.0-
    "mY5R+ZIWxy5BDEEZTeWlHQ", "WatchSupportsSiriCommute", // iOS pre-12.0
    "MYKMJDMFE/lhvOVXgtDNuw", "RendersLetterPressSlowly", // iOS pre-12.0
    "myx96YOqBSDzLwljSYWBiQ", "ProductTypeDescForCamera", // iOS 26.0
    "mZfUC7qo4pURNhyMHZ62RQ", "BuildVersion", // iOS pre-12.0
    "n/aVhqpGjESEbIjvJbEHKg", "SphereCapability", // iOS pre-12.0
    "n6blIRZ4IumqHl/toNJcpg", "ScreenCaptureHeight", // iOS 26.0-
    "N8lZxRgC7lfdRS3dRLn+Ag", "HEVCDecoder8bitSupported", // iOS pre-12.0
    "na6PSBfq05lkAfWkwAwaGg", "ExternalPowerSourceConnected", // iOS pre-12.0
    "NaA/zJV7myg2w4YNmSe4yQ", "WifiChipset", // iOS pre-12.0
    "nAl8QWlApaJQkipRf38fdg", "DeviceSupportsNewton", // iOS pre-12.0
    "ND6ZSbBBgMgwtMfh+OL5Wg", "HighestSupportedVideoMode", // iOS pre-12.0
    "NDnoY3adyyskgiIQBNtlyQ", "DeviceIsNED", // iOS 26.0-
    "NE090Fbwd79LVOHj0AN+OA", "RecoveryOSVersion", // iOS 26.0-
    "nfR1IphTGCaoFNu3NrCtWQ", "DeviceSupportsDynamicEndOfChargeLegacyHW", // iOS 26.0-
    "nFRqKto/RuQAV1P+0/qkBA", "UniqueDeviceIDData", // iOS pre-12.0
    "nhGhVMyvrWYe9U2ltAUImg", "ArrowChipID", // iOS 26.0-
    "Nhm02nvVOaQPimpOshlO1g", "FaceTimeBitRate2G", // iOS pre-12.0
    "niQFEBBY7JaauAIosAyQQg", "MultiLynxPublicKeyArray", // iOS 26.0-
    "NJsxTSI2WuD+13rxShXX9w", "DeviceHousingColor", // iOS pre-12.0
    "nJU6/TSuJTVJlJ7t5/Z/ug", "DeviceSupportsMapsOpticalHeading", // iOS 26.0-
    "njUcH4bm+JBmvASakDdObg", "LiDARCalibrationPrCL", // iOS 26.0-
    "nK4D+jDUuTGFFwRFPC2lWg", "DeviceSupportsFloorCounting", // iOS pre-12.0
    "NLWYUp5icK9sRsPDI7XJtw", "IsComputeController", // iOS 26.0-
    "Nmhz54v5ZLqj2I4NPFIFqQ", "BasebandSerialNumber", // iOS pre-12.0
    "nmOy2K5HzAAs2QNAi8wR+Q", "SupportsRotateToWake", // iOS pre-12.0
    "noqTy5fUbyK03UHxWigBBQ", "OLEDDisplay", // iOS pre-12.0
    "NPzjaX07XnS4KcMZ+l8ymA", "ExternalChargeCapability", // iOS pre-12.0
    "NrXe/KHDNhJ4r2SC2bMQyA", "any-telephony", // iOS pre-12.0
    "nSo8opze5rFk+EdBoR6tBw", "RestrictedCountryCodes", // iOS pre-12.0
    "NszbG6qiAztVal4mpDQRkg", "CameraAppUIVersion", // iOS 26.0-
    "nteaxwXwZWYUI9z46VDRnA", "video-camera", // iOS pre-12.0
    "NUYAz1eq3Flzt7ZQxXC/ng", "FirstPartyLaunchTimeLimitScale", // iOS pre-12.0
    "nv4RoLkNoPT0/rsO8Yaiew", "still-camera", // iOS pre-12.0
    "nVh/gwNpy7Jv1NOk00CMrw", "MedusaPIPCapability", // iOS pre-12.0
    "NwdAF2t/rQxcHdIaRlZxMA", "SoCSKU", // iOS 26.0
    "nWFV2qG2TjSuH7vZFCdi4w", "RearFacingCameraModuleSerialNumber", // iOS pre-12.0
    "nXbrTiBAf1dbo4sCn7xs2w", "DeviceSupportsFindApplePencil", // iOS 26.0-
    "NXJOYK7VhNn7ugbF2kx0zg", "3GProximityCapability", // iOS pre-12.0
    "Nzu4E/VsXjEIa83CkRdZrQ", "Image4CryptoHashMethod", // iOS pre-12.0
    "nZUUCFZgomfWUIPGGzNAqg", "SecureElementID", // iOS pre-12.0
    "O/7gbXWA5X2IRPVtDRU+bw", "OnDeviceSiriCapability", // iOS 26.0-
    "o/mXrucvBSYUXqq7K3UzKA", "IsThereEnoughBatteryLevelForSoftwareUpdate", // iOS pre-12.0
    "o0axLo6LGt8HbuEWdLZ92Q", "auto-focus-camera", // iOS pre-12.0
    "o60T6wXe1DDaO4a4gw10TA", "TristarID", // iOS pre-12.0
    "O8mk69g6k/CbfeET9LtqQA", "RosalineSerialNumber", // iOS pre-12.0
    "oAX1wYJl2iL3BX2G9LA7iw", "ExclaveCapability", // iOS 26.0-
    "oBbtJ8x+s1q0OkaiocPuog", "MainScreenStaticInfo", // iOS pre-12.0
    "OBqqs000I0SR+EbJ7VO8UQ", "HasSpringBoard", // iOS pre-12.0
    "ocYC+NyuthjbvU9CyI4Z8Q", "FrontFacingCameraStageLightPortraitCaptureCapability", // iOS 26.0-
    "og9DE42ZUHzzTiVpxwOmqw", "UnifiedGamingPerfLeveliPadTier1", // iOS 26.0
    "ohnQBWkVQf2nu9Vr/9uLug", "DeviceSupports3DImagery", // iOS pre-12.0
    "OHXV8ldryg9nrOCapcyDCQ", "ReceiveARCStreamOverAirPlayCapability", // iOS 26.0-
    "oJGeec0N+MudCr0LsdtbHw", "MobileSubscriberNetworkCode", // iOS pre-12.0
    "Oji6HRoPi7rH7HPdWVakuw", "HasInternalSettingsBundle", // iOS pre-12.0
    "OjzOua0LkOegX7pQdgMksw", "main-screen-height", // iOS pre-12.0
    "ol92SaBpqIvQs+KBljuwGA", "kConferenceCallType", // iOS pre-12.0
    "oLjiDs+BWEdMVbjE0x6cnw", "DeviceSupportsStudioLightPortraitPreview", // iOS pre-12.0
    "OoFyZnd3oLS2Lw/KQTccGA", "SupportsTouchRemote", // iOS pre-12.0
    "oOV1jhJbdV3AddkcCg0AEA", "apple-graphics-performance-tier", // iOS 26.0-
    "oPeik/9e8lQWMszEjbPzng", "ArtworkTraits", // iOS pre-12.0
    "OPzhvROZUqCZhgYMyve5BA", "sms", // iOS pre-12.0
    "oQNDePXjSD1z7W0ddqt9tg", "HWModelDescriptionForAutomatedTesting", // iOS 26.0
    "OWi11Urd09rDmPVy1z5dOQ", "CoverglassSerialNumber", // iOS pre-12.0
    "OWLyWlUOIkl+eQB7Iq37xQ", "DesenseBuild", // iOS pre-12.0
    "oWUSugFxOVhHOKYv7DawLw", "DeviceSupportsSWProRes", // iOS 26.0-
    "OyENNqRhuo8+RHkpbr/82A", "RoswellChipID", // iOS pre-12.0
    "oYicEKzVTz4/CxxE05pEgQ", "TargetSubType", // iOS 26.0-
    "P5Go9WVVA604m7rKhbVndw", "ProductVersionExtra", // iOS 26.0-
    "P6z8eNrRPcv0AcKPML0iow", "wi-fi", // iOS pre-12.0
    "paR6NqTecAD44x45kzV87g", "AudioPlaybackCapability", // iOS pre-12.0
    "pB5sZVvnp+QjZQtt2KfQvA", "BasebandChipset", // iOS pre-12.0
    "pCbWB0w5vhsKbGJHs/c1jQ", "youtube", // iOS pre-12.0
    "PcQWbThCb7iLEW+EoqZdEQ", "NandControllerUID", // iOS pre-12.0
    "PdprWthPO6YyrO6p1vLRgQ", "VolumeDownButtonCGRect", // iOS 26.0-
    "PFnuFyqMMnGUQQnTqS5byg", "DeviceSupportsAbsoluteAltimeter", // iOS 26.0-
    "pFpC81KCZegLf4FenQZ2OA", "multitouch", // iOS 26.0-
    "PJKxdi6epBZAu1rqAsrcjQ", "AV1DecodingCapability", // iOS 26.0-
    "plaYa8bKJaAF5Erc5nvZ+g", "RearFacingCameraBurstCapability", // iOS pre-12.0
    "PLQ6xgfGji63NbFu+sjeYg", "WLANBkgScanCache", // iOS pre-12.0
    "pLzf7OiX5nWAPUMj7BfI4Q", "SupportsIrisCapture", // iOS pre-12.0
    "pMeQxE5szZTjLMk10TisDQ", "UserIntentPhysicalButtonCGRect", // iOS pre-12.0
    "PNexcW/LBlPgAm+Skp2EAg", "EffectiveProductionStatusSEP", // iOS pre-12.0
    "Po0s2Vf6g2ZqymKGNLFxeQ", "FaceTimeCameraSupportsHardwareFaceDetection", // iOS pre-12.0
    "po7g0ATDzGoVI1DO8ISmuw", "RearFacingCameraVideoCapture4kMaxFPS", // iOS pre-12.0
    "PpmzzBVLpZVubmP0tCIymg", "WirelessChargingCapability", // iOS pre-12.0
    "pQzfsK0Ado+nkNFgPRIA8Q", "DeviceSupportsLivePhotoAuto", // iOS pre-12.0
    "PQzmRjKVMistuIVsqs6QXA", "BasebandFirmwareVersion", // iOS pre-12.0
    "PR+xeEtTAiUN0R25+EYGfw", "DeviceSupportsCarPlay2", // iOS 26.0-
    "PsIXZ7uVWznKaTEXDbFSYA", "CameraButtonCGRect", // iOS 26.0-
    "psOb+c5by4e5OqReDiFm7w", "DeviceCoverGlassCoating", // iOS 26.0-
    "PTfO3r9syJ45k+OItTlD3Q", "ui-no-procedural-wallpaper", // iOS pre-12.0
    "PTQ+ABwag03BwO/CKvIK/A", "DeviceSupportsSiriSpeaks", // iOS pre-12.0
    "PUMArrha4PFeOqINeQRM3A", "sim", // iOS pre-12.0
    "PVMLomcejavaax8/I3Ud3A", "RearALSCapability", // iOS 26.0-
    "pX2TxZTxWKS7QSXZDC/Z6A", "HasBattery", // iOS pre-12.0
    "PxEDp0oOasJ92F/V7YBa8A", "RawPanelSerialNumber", // iOS pre-12.0
    "PxLTGkQx9GkeYcJKOaZguA", "video-stills", // iOS pre-12.0
    "Q1Ty5w8gxMWHx3p4lQ1fhA", "MLBSerialNumber", // iOS pre-12.0
    "Q2jR+AUT9PTHUrP/mkdfxQ", "NVRAMDictionary", // iOS pre-12.0
    "q3JBrhzy5fyJ1+LAITPW0w", "BluetoothLE2Capability", // iOS 26.0-
    "q4cLktMwtrx8dCJAQTeqTg", "PanoramaCameraCapability", // iOS pre-12.0
    "Q5QHkCRPRmiX3L/5xxKrRg", "BasebandCertId", // iOS pre-12.0
    "q69vauqK9djnPlEZBFBV4A", "DeviceSupportsSiDP", // iOS pre-12.0
    "qb//mYg6KeTmjv8w4ZAMIg", "CompassCalibration", // iOS pre-12.0
    "QbQzuIbef01P4JeoL9EmKg", "DeviceSceneUpdateTimeLimitScale", // iOS pre-12.0
    "QdL5XM6PGBrjvJ/k187Ueg", "IDAMCapability", // iOS pre-12.0
    "qeaj75wk3HF4DwQ8qbIi7g", "DeviceSupportsEnhancedMultitasking", // iOS 26.0-
    "QFnvO2shAYI+d4bj3qXuFQ", "DevicePrefersBuildingStrokes", // iOS pre-12.0
    "qgfS+6l1exvcMW5Tfplv2Q", "OceanComputeCarrierID", // iOS 26.0-
    "QGmb9t2ZMFVwOImO6fewgQ", "all-features", // iOS pre-12.0
    "qHVhw5NhezD+ljFUPvQb4g", "nike-ipod", // iOS pre-12.0
    "QHxt+hGLaBPbQJbXiUJX3w", "DeviceSupportsBootChime", // iOS 26.0-
    "QJSuJ2zhdxYX/7DUA2JtUw", "EffectiveSecurityModeSEP", // iOS pre-12.0
    "qlcdNkarcGLcbW3HvBhwaA", "FrontFacingCameraModuleSerialNumber", // iOS pre-12.0
    "qNNddlUK+B/YlooNoymwgA", "ProductVersion", // iOS pre-12.0
    "qOwiNS0eFEq9oi3MNsgxWg", "FirmwarePreflightInfo", // iOS pre-12.0
    "Qq9/Mya05P4ToEr1pMpGGg", "BootManifestHash", // iOS pre-12.0
    "qRxbmK4B8fGc06Iwe8YptQ", "ADSCapability", // iOS 26.0-
    "QtLcewkuPtPV0RpO+i0Zzw", "MarketingVersion", // iOS pre-12.0
    "QuSuh/r6w4M730U5XhKzrg", "DeviceSupportsVSHCompensation", // iOS 26.0-
    "QVwCp3Lu9RLnxw7LO9DBfQ", "RearFacingCameraTimeOfFlightCameraCapability", // iOS 26.0-
    "qWG594bTi87edQCSYxlLeA", "EUICCChipID", // iOS pre-12.0
    "qWGVjnlN/wWMhlWgfNcSBg", "DeviceSupports9Pin", // iOS pre-12.0
    "qwXfFvH5jPXPxrny0XuGtQ", "BuildID", // iOS pre-12.0
    "QZgogo2DypSAZfkRW4dP/A", "InternationalMobileEquipmentIdentity", // iOS pre-12.0
    "qzHhHrOpIDLAq2balBdVZg", "RingerButtonCGRect", // iOS 26.0-
    "r5pA2qLgR86BQKwgMjPWzg", "LynxSerialNumber", // iOS pre-12.0
    "r5QUsvvgcb2Qmuflua13fQ", "DeviceRequiresProximityAmeliorations", // iOS pre-12.0
    "RA3I5nhSK65i1ZxkRxQKfg", "HasThinBezel", // iOS pre-12.0
    "RbiXiBQAmypd3Btw3jADAw", "DeviceSupportsAppleLPM", // iOS 26.0-
    "re6Zb+zwFKJNlkQTUeT+/w", "UniqueDeviceID", // iOS pre-12.0
    "RECLuzbJ6oh8q4NKR8RtNg", "multitasking", // iOS pre-12.0
    "rGc8UCjL0zBt51mv81FtIg", "DeviceSupportsActiveNFCReadingOnly", // iOS 26.0-
    "RgoxDxYGuZ0GzijFt6kSQQ", "StockholmJcopInfo", // iOS pre-12.0
    "rJkMAGeVLdhP5+10G5hVcA", "UserIntentPhysicalButtonCGRectString", // iOS pre-12.0
    "rJl1HTk57uav5OTZZAyc6g", "DeviceSupportsWatchSpeakerPlayback", // iOS 26.0-
    "rkFHO5dZmWxy3QdOx7r7kA", "MobileEquipmentInfoCSN", // iOS pre-12.0
    "rkqlwPcRHwixY4gapPjanw", "DeviceName", // iOS pre-12.0
    "RLlZndRrTB3oIDuZEihtpQ", "RearFacingCameraAutoHDRCapability", // iOS pre-12.0
    "RNcdWbM8+dO5tx82A+YCcQ", "ProvisioningUniqueDeviceID", // iOS 26.0-
    "rtIWWK0kM4F+ZMkIqhE7yQ", "DeviceStingHousingColor", // iOS 26.0-
    "RvCUAjrf7O/zAzV1StnBlg", "IsComputeNode", // iOS 26.0-
    "rXbje18EX3b6I7u/pXBYeg", "RequiresPairedRemote", // iOS 26.0-
    "rxUlSnmihTL8oDg9Hrgq/A", "MixAndMatchPrevention", // iOS pre-12.0
    "RXyKSjeF239SL2vOcru01A", "MobileEquipmentInfoBaseVersion", // iOS pre-12.0
    "ry09Fs7QIF3ITE0Fx5OdvQ", "RearFacingCameraVariableFrameRateCapability", // iOS 26.0-
    "RYO2N0gqp5hHCik2TEiSVA", "armv7s", // iOS pre-12.0
    "RyXm3yMC4ejlFvwlEI509w", "hearingaid-low-energy-audio", // iOS pre-12.0
    "RYZZuAFEfSNnEKEzwzRnqw", "photo-stream", // iOS pre-12.0
    "s+gaKNe68Gs3PfqKrZhi1w", "MonarchLowEndHardware", // iOS pre-12.0
    "s2qnnwugvb7yAD70+Uho7g", "HapticsPowerControlFeatures", // iOS 26.0-
    "s2UwZpwDQcywU3de47/ilw", "microphone", // iOS pre-12.0
    "s7nuHoZIYNoOHCqT9iyZkQ", "DeviceSupportsInductiveCharging", // iOS 26.0-
    "s8TgWYc7BjtSNbtuycqauw", "DeviceSupportsLaguna", // iOS 26.0-
    "SAGvsp6O6kAQ4fEfDJpC4Q", "IsSolariumLowPerformanceDevice", // iOS 26.0
    "SaW+DA+cbiqDHrex8MTABA", "DeviceSupportsEnvironmentalDosimetry", // iOS 26.0-
    "SbXytSPZXB1jQ8GLZOxCPw", "VolumeDownButtonNormalizedCGRect", // iOS 26.0-
    "SCNOHu+KqRX0xhIlj5KXaA", "H264EncoderCapability", // iOS pre-12.0
    "sFTm4FEVKVfdZ0ChdwQY1g", "WifiAntennaSKUVersion", // iOS pre-12.0
    "sHiXbHqHvvRS3I/qo/rH2Q", "SIMTrayStatus2", // iOS pre-12.0
    "sI1x188eYDcARhSzXxk3Cg", "iphone-performance-gaming-tier", // iOS 26.0-
    "sigsyX/a/CpMjoZnrgwIgg", "HEVCDecoder12bitSupported", // iOS pre-12.0
    "sJ0n0UZHSUVJbmyy2p54Cw", "unified-ipod", // iOS pre-12.0
    "sjGZBQzow3yV/IOa0wCeoQ", "VMUniqueDeviceIDData", // iOS 26.0-
    "sJmYs82RucA1MWX5jHFSjA", "DeviceSupportsWebkit", // iOS pre-12.0
    "SjQQ07G8UacM7E69G7dPbg", "DeviceSupportsSpatialOverCapture", // iOS 26.0-
    "sLe8lqXRlqZM74MNUoVcyQ", "BatteryIsCharging", // iOS pre-12.0
    "SMgTCc2v9AU2ziIHRX8qww", "hearingaid-audio-equalization", // iOS pre-12.0
    "SmUPjD77AHIMCLny9nawdw", "ConfigNumber", // iOS pre-12.0
    "SNfDJgQFV2Xj7+WnozcJPw", "main-screen-scale", // iOS pre-12.0
    "sNm4HYxfChAt48rf54qAyQ", "EphemeralDataModeEnabled", // iOS 26.0-
    "spGVujDEmyCzDznXozB3oA", "apn", // iOS pre-12.0
    "sQwlfROu8fcD1Qwm8YJVeg", "DeviceSupportsReverseZoom", // iOS 26.0-
    "SR/QIL//glHfqoE+lOAnbA", "SupportsBurninMitigation", // iOS pre-12.0
    "ssIPnsZyWHPGC5sg3Pzkiw", "SiKACapability", // iOS pre-12.0
    "STBQ8gY0pl0CK8VmRcks4w", "RearFacingCameraFocusPixelCalibrationCapability", // iOS 26.0-
    "SvI9oDkzw4XJFd+dKen/2Q", "DeviceVariant", // iOS pre-12.0
    "SZy8T5ma/+a0wJc0ntiaaA", "PhoneNumber2", // iOS 26.0-
    "T0FD6BT+PiWc2duMVlTRww", "DeviceIsPortableMac", // iOS 26.0-
    "TACCxk6y28d14yJN09RtTg", "DeviceSupportsLanguageDownloadUI", // iOS 26.0-
    "tad3RCjcWdkyLSVI8kUBtA", "caller-id", // iOS pre-12.0
    "tbBVomzeDyPq15QV5VGQGg", "DeviceSupportsVoiceOverCanUseSiriVoice", // iOS 26.0-
    "tbdNCtok0BwuLN11WwnwsQ", "DeviceSupportsAutoDim", // iOS 26.0-
    "tBrEf4ccS4Q6wtUiNB0WKw", "DeviceSupportsLongFormAudio", // iOS 26.0-
    "TDM8SEI14n2KE9PGHO0a4A", "FrontFacingCameraStillDurationForBurst", // iOS pre-12.0
    "tdUWKiiM7JdctnzQuvaVVA", "c2k-device", // iOS pre-12.0
    "TF31PAB6aO8KAbPyNKSxKA", "UniqueChipID", // iOS pre-12.0
    "THo7EIAWJiQExmTeHpevLg", "FrontFacingCameraVariableFrameRateCapability", // iOS 26.0-
    "TLU8Pwcsys+5y2UFoMOjPA", "DeviceCoprocessorIsT1", // iOS 26.0-
    "ToJGxfcjkIerYyeL2e8c4A", "BasebandBoardSnum", // iOS pre-12.0
    "ToLFRidm+eJGWnpw6W4Wwg", "HumanReadableProductVersionString", // iOS 26.0-
    "TpY9O1U1rtUk/m0BvlO58A", "DeviceDefaultsToAnalyticsOptIn", // iOS 26.0-
    "TqAfAH10ANDgiG7V2u8BkQ", "FrontFacingCameraHFRVideoCapture720pMaxFPS", // iOS 26.0-
    "Tqr2NqCLwGszJc3HOaPlTw", "driverkit", // iOS 26.0-
    "TqrlqJOZiAuRx8Qu3SVr+Q", "SecondaryWifiMacAddressData", // iOS pre-12.0
    "TqtrpIdOXIIlhOraMmq/pQ", "ipad-minimum-performance-m1", // iOS 26.0-
    "TR6Z82EVZEKMVUdHfkhDmQ", "DeviceSupportsBrook", // iOS 26.0-
    "Tr9qG122eEQiKGfr6EGRdQ", "RegionalBehaviorEUVolumeLimit", // iOS pre-12.0
    "trBC4VS5gVmCv6Wg41Hryw", "DeviceSupportsFairPlaySecureVideoPath", // iOS 26.0-
    "TTZrMo1OOEUELa7asaQ7xg", "RearFacingCameraHDRCapability", // iOS pre-12.0
    "tUIqcYyzHuWBvBQHsLk8IQ", "international-settings", // iOS pre-12.0
    "tuwdHA2NDGnLajCo5K3UUA", "voice-control", // iOS pre-12.0
    "TXZxlSojLMQyLqusm9aa/g", "DeviceEnclosureRGBColor", // iOS pre-12.0
    "Ty4lICNS1jQh45sB3wQd7A", "AlwaysOnDisplayMaxMemory", // iOS 26.0-
    "Ty5/C8UDfdjcdR853kulmA", "FrontFacingCameraBurstCapability", // iOS pre-12.0
    "tYqUcLmLfhmk7vOgdFvURg", "sim-phonebook", // iOS pre-12.0
    "TZ/0j62wM3D0CuRt+Nc/Lw", "ProductHash", // iOS pre-12.0
    "U+73bmG4kBGj6kpreQXUTQ", "DeviceSupportsAlwaysListening", // iOS pre-12.0
    "U/nyu97+Q5SFY9yJKJTuSA", "TopModuleAuthChipID", // iOS 26.0-
    "u3c0R+31Df4SUTHrICQkTg", "hearingaid-power-reduction", // iOS pre-12.0
    "uAIY4Jb2A7Fy2aLrlDU1gg", "RemoteBluetoothAddress", // iOS pre-12.0
    "UAMiw+ItKRaA1yk2uyzKGQ", "UnifiedGamingPerfLeveliPadTier2", // iOS 26.0
    "uB6I2WImAHd8DEGuqYcMbw", "WifiFirmwareVersion", // iOS pre-12.0
    "UCG5MkVahJxG1YULbbd5Bg", "MedusaOverlayAppCapability", // iOS pre-12.0
    "uCIk6n9Am5fsV2cTjhqFQw", "HWModelDescriptionForAnalytics", // iOS 26.0
    "UCLOC2TKe3vRkId34ubKWw", "AmbientLightSensorSerialNumber", // iOS pre-12.0
    "UcRWpMcvJDfLzn6utLj3XQ", "ApNonceRetrieve", // iOS pre-12.0
    "ud+MF+BkcM1zeTxPJCsHpg", "FrontFacingLowLightCameraCapability", // iOS 26.0-
    "UDftNoVOBIs9cSeia57q1A", "DeviceHasEmbeddedSIMOnlyBoard", // iOS 26.0-
    "ueuuYQk48HGWm/cJlHq/Dw", "fcc-logos-via-software", // iOS pre-12.0
    "UFqkf9tcH1ltsOMzpdwSUw", "multitasking-gestures", // iOS pre-12.0
    "ugia43pinTp0pukSIYQ7uA", "DeviceSupportsBeacon", // iOS 26.0-
    "UHwjAM1cqBLCR1OuYouf8A", "PhotoSharingCapability", // iOS pre-12.0
    "uKc7FPnEO++lVhHWHFlGbQ", "ipad", // iOS pre-12.0
    "uksZ8eaKeV5sUpLNBPafww", "FrontCameraOffsetFromDisplayCenter", // iOS pre-12.0
    "ulMliLomP737aAOJ/w/evA", "IsSimulator", // iOS pre-12.0
    "uO3aPe7lfB1XxSiz/1xBvA", "CertificateProductionStatus", // iOS pre-12.0
    "UoeNJcQ336tc+F5/1r4tqQ", "DeviceSupportsAdvancedMapRendering", // iOS 26.0-
    "uyejyEdaxNWSRQQwHmXz1A", "DiskUsage", // iOS pre-12.0
    "UZfUiD1Aqy3GOwg72SQcLQ", "RearFacingSuperWideCameraModuleSerialNumber", // iOS 26.0-
    "UZyrJHlX635ocWEjBkt9YA", "UIProceduralWallpaperCapability", // iOS pre-12.0
    "V0d6pv080gHL3QQWNs9aog", "DeviceSupportsLowPowerSoundClassification", // iOS 26.0-
    "v2Q3tLoD4+o/XazHC/0FyA", "DeviceSupportsYCbCr10", // iOS pre-12.0
    "V2Ykm/0M3CA6nyNhwNInsg", "64-bit", // iOS pre-12.0
    "v5YVEwERRin1v+reUNjJ5w", "ComputerName", // iOS pre-12.0
    "V9pLLbPQhyb75bbdTioZVw", "DeviceSupportsHardwareDetents", // iOS pre-12.0
    "v9YZN998zL0OLA3q6SpPQA", "HasIcefall", // iOS pre-12.0
    "vaiFeAcMTIDXMSxTr8JwCw", "BasebandPostponementStatus", // iOS pre-12.0
    "VasUgeSzVyHdB27g2XpN0g", "SerialNumber", // iOS pre-12.0
    "VdSOpM2K054AhCKBaXuiqw", "MacBridgingKeys", // iOS 26.0-
    "vENa/R1xAXLobl8r3PBL6w", "EffectiveSecurityModeAp", // iOS pre-12.0
    "VG9TCKNqNLCHk0J6zTkuVQ", "EthernetMacAddress", // iOS pre-12.0
    "VGDDUFPWHbX/Ie9RSI0yDQ", "DeviceIsMuseCapable", // iOS 26.0-
    "VHTcx7WQq0V7YgGKZisRWA", "FDRSealingStatus", // iOS pre-12.0
    "vIccod02kDxScKF5s2h6OA", "BasebandUniqueId", // iOS pre-12.0
    "VikxgsK3LmzdJGsKgCEZLA", "IsFactorySignedRestore", // iOS 26.0-
    "vl45ziHlkqzh1Yt6+M9vBA", "displayport", // iOS pre-12.0
    "VLfT+eziZYKNjRASM6ntnQ", "FirmwareNonce", // iOS pre-12.0
    "vme9Buk6XiWFCXoHApxNFA", "MarketingDeviceFamilyName", // iOS 26.0-
    "VqRhf8vgXr9B+SYvpnX39g", "BoardRevision", // iOS 26.0-
    "VuGdqp8UBpi9vPWHlPluVQ", "CompatibleAppVariants", // iOS 26.0-
    "W/xqvBX9L07XHb0BOtYycQ", "ThreadRadioMacAddress64Bit", // iOS 26.0-
    "W7MyZ3Yxoy1qD6FrI0mLUQ", "RF-exposure-separation-distance", // iOS pre-12.0
    "WAfNjeiwOd/k6+VU6D6SIQ", "ExtendedLOMMacAddress", // iOS 26.0-
    "waGD2UTpntjbDXD1r3oALQ", "DeviceSupportsSiriHub", // iOS 26.0-
    "waWRQ4fj6cyMuJ+wTWJs1g", "RearCameraOffsetFromDisplayCenter", // iOS pre-12.0
    "wBVgxg3VYUU5gawcgq7MXg", "SupportedKeyboards", // iOS pre-12.0
    "WC6wwFV23k19BlUQIAwDTg", "RearFacingCameraMaxVideoZoomFactor", // iOS pre-12.0
    "wH7fRq4TDdYG2pN1KDQW/A", "FrontFacingIRStructuredLightProjectorModuleSerialNumber", // iOS pre-12.0
    "whbsdxpLirBFgUbLH3+0JA", "DeviceSupportsAdaptiveMapsUI", // iOS pre-12.0
    "wlxZYdEZITDTzgs/OnnV+Q", "personal-hotspot", // iOS pre-12.0
    "wNdWl5xfBJmJGNWJr5t0zA", "DeviceSupportsBerkelium2", // iOS pre-12.0
    "wOVK1nhmiAawowdbIwgyaQ", "RearFacingCameraVideoCaptureFPS", // iOS pre-12.0
    "WPEkba78QeFFU/wgqpOx6w", "UserIntentPhysicalButtonNormalizedCGRect", // iOS pre-12.0
    "Wr2SycNVQwBrdup3ok+LxQ", "SpeakerCalibrationSpTS", // iOS pre-12.0
    "WTpITolfF3P09otI1pn2gw", "DeviceSupportsUntrustedRemoteSysdiagnose", // iOS 26.0-
    "wtUF1NceYeLT6IHovZvocw", "DeviceSubBrand", // iOS pre-12.0
    "wu9wv8HhpA95iHT4Yyez7A", "SecurityDomain", // iOS 26.0-
    "WXi7NQbOKnEX4vPQFeZAdQ", "DeviceSupportsSiriBargeIn", // iOS 26.0-
    "wYMBabAO8VguyDDVgCsPdg", "WiFiChipsetRevision", // iOS 26.0-
    "X5yfJDYNipZXIS8R2a7RmA", "DeviceSupportsWalkingRadiusAnimation", // iOS 26.0-
    "X6NGcYcvHmbqlR8hLXASJA", "DeviceSupportsSpatialAudioCapture", // iOS 26.0
    "X7SF9XDG+CBhoPIXA1YlCg", "ThreadRadioMacAddressData", // iOS 26.0-
    "X9cK3qXzcFCrVpE258P2lQ", "horseman", // iOS 26.0-
    "Xa9nxhMDoHTdmrn/FufA3g", "WatchSupportsListeningOnGesture", // iOS pre-12.0
    "xbNo7dj2oAnz92JhEOn9tw", "DevicePrefers3DBuildingStrokes", // iOS pre-12.0
    "xDg5n/9rR2cMhp7MK0irBA", "healthkit", // iOS pre-12.0
    "xdqMcsaQm05nJtJnLNVRBA", "DeviceSupportsGammaContrastPreservation", // iOS 26.0
    "XellXEQUbOIgUPoTrIj5nA", "RearFacingCameraHFRVideoCapture720pMaxFPS", // iOS pre-12.0
    "XEoV4os3FAUL7yHDxWmSMw", "AppStore", // iOS pre-12.0
    "XEzIXVPlevxuEIpZrMY+8A", "Skey", // iOS pre-12.0
    "XFtUsQP3AyqT4CazSb5VCw", "DeviceSupportsCarIntegration", // iOS pre-12.0
    "XFx5cRZ0tJYl+xJUCEgjnQ", "NFCRadioCalibrationDataPresent", // iOS pre-12.0
    "XI87Zkcr5j1B/p2dom/B6A", "AWDLCapability", // iOS pre-12.0
    "XIcF5FOyQlt/H79oFw9ciA", "PipelinedStillImageProcessingCapability", // iOS pre-12.0
    "XjG5q4m+sX+F9Prap4MBAQ", "IsComputePacketBridge", // iOS 26.0
    "xJUG7IKySthRrPcxII184g", "enforce-shutter-click", // iOS pre-12.0
    "XkfGVYlrkBQJgaGabHESJQ", "DeviceSupportsDClr", // iOS pre-12.0
    "xleedMDMw0UV3fSgmHIoaQ", "kSimultaneousCallAndDataCurrentlySupported", // iOS pre-12.0
    "XmExwNGRvYTII6QC0+jvsA", "MaximumScreenScale", // iOS pre-12.0
    "XNCjqOupLM/S8fNyxRNQTA", "DeviceSupportsPhotosInpainting", // iOS 26.0-
    "xNN67KktpWp7syTT3S1BFA", "ProductTypeDescForAnalytics", // iOS 26.0
    "XnXl4MhKZx3zRKvA7ZwIYQ", "DeviceLowBatteryLevel", // iOS 26.0-
    "xOEH0P1H/1jmYe2t54+5cQ", "MobileEquipmentIdentifier", // iOS pre-12.0
    "xOJfWykLmQCc8lKlzMlrLA", "assistant", // iOS pre-12.0
    "xojWvSTQWT7Icy+xfVzjAQ", "FramebufferIdentifier", // iOS 26.0-
    "XQBHOWjPt2P+uNqlLm1P7A", "BasebandClass", // iOS pre-12.0
    "xqvkN8MjIzTv37omKFzrwg", "DeviceSupportsLiveVideoRendering", // iOS 26.0-
    "XriAxQ+JY1z5nt5f3ftXVw", "DeviceSupportsCameraHaptics", // iOS pre-12.0
    "XrPbSCNx9X7Lyw9oGPgMDQ", "WirelessBoardSnum", // iOS pre-12.0
    "xRyzf9zFE/ycr/wJPweZvQ", "InternationalMobileEquipmentIdentity2", // iOS pre-12.0
    "xsaMbRQ5rQ+eyKMKG+ZSSg", "PasswordConfigured", // iOS pre-12.0
    "xSh3mf5+Zuoz6xhxEah0zQ", "DeviceSupportsTethering", // iOS pre-12.0
    "XSLlJd/8sMyXO0qtvvUTBQ", "bluetooth", // iOS pre-12.0
    "xU1eZLRifcixnyDzjo52DQ", "tv-out-crossfade", // iOS pre-12.0
    "xUHcyT2/HE8oi/4LaOI+Sw", "PartitionType", // iOS pre-12.0
    "xunfK8NYNCS75N2z2buKWQ", "FaceTimeBitRateLTE", // iOS pre-12.0
    "XWAyufZ2SrclH9F9EDmBKw", "AcousticID", // iOS 26.0-
    "XxnEk9uiIk5vCdbWEGt7lA", "DeviceSupportsLiquidDetection_CorrosionMitigation", // iOS pre-12.0
    "XYlJKKkj2hztRP1NWWnhlw", "ResearchFuse", // iOS 26.0-
    "xYu8vn4nnbLnNTbBe0FT+w", "WAGraphicQuality", // iOS pre-12.0
    "xZm4Ky2/qswyf7ykvlchYg", "CPUType", // iOS pre-12.0
    "y0jtYciPmcx3ywPM582WZw", "ContinuityCapability", // iOS pre-12.0
    "Y2TwC8z+XeBBBswnLf7JsQ", "PeekUIWidth", // iOS pre-12.0
    "Y2Y67z0Nq/XdDXgW2EeaVg", "FMFAllowed", // iOS pre-12.0
    "y4GIxpQP4MO/j3wWUJdiyg", "DeviceSupportsAvatars", // iOS 26.0-
    "y5dppxx/LzxoNuW+iIKR3g", "DeviceCornerRadius", // iOS pre-12.0
    "YAbRmHobt+BRHuSPm2OGQw", "DeviceSupportsVirtualResearchEnvironment", // iOS 26.0-
    "yAfB6E2v0++rHtdW7SDg8w", "HWModelDescriptionForCamera", // iOS 26.0
    "ybGkijAwLTwevankfVzsDQ", "MainScreenCanvasSizes", // iOS pre-12.0
    "YdPNjYPBzyE0jJl2X/CayQ", "RotateToWakeStatus", // iOS pre-12.0
    "yF2IQrYS4yyREV4ZkbLysw", "ThreadRadioMacAddress64BitData", // iOS 26.0-
    "yf309VokHnvuZ4SyOixR5A", "HasPartiallyOccludedDisplay", // iOS 26.0-
    "YgC2TeHCEwzJ/ixqmNCzwQ", "DeviceHasNAN", // iOS 26.0-
    "yhHcB0iH0d1XzPO/CFd3ow", "DeviceSupportsApplePencil", // iOS pre-12.0
    "YiUtBQygkHRhLcdO3LFB4A", "DeviceSupportsTelephonyOverUSB", // iOS 26.0-
    "yjP8DgByZmLk04Ta6f6DWQ", "PartitionStyle", // iOS 26.0-
    "ykpu7qyhqFweVMKtxNylWA", "DeviceSupportsAODVibrancy", // iOS 26.0-
    "yl8qmYPdAhFLeDBho10sdQ", "FaceTimeDecodings", // iOS pre-12.0
    "YlEtTtHlNesRBMal1CqRaA", "DeviceSupportsDynamicIsland", // iOS 26.0-
    "yLfrxjB6AbZTASUIAcqi2Q", "AutomaticMicMode", // iOS 26.0-
    "YlK+0xmxNWhNn/+r8SM8kA", "DeviceSupportsStereoAudioRecording", // iOS pre-12.0
    "yMmSdMRKEHRTCQ72ltCH1w", "airplay-mirroring", // iOS pre-12.0
    "yNesiJuidlesNpI/K5Ri4A", "PasswordProtected", // iOS pre-12.0
    "yPqGUljqvtItkM6XMCZaQw", "DisplayDriverICChipID", // iOS 26.0-
    "yRZv0s7Dpj8ZBk0S+0+nMA", "contains-cellular-radio", // iOS pre-12.0
    "yUCaqT4KOwJpYEb+XDPq7g", "SIMStatus", // iOS pre-12.0
    "YUobJKXH3+ukrUe13TXL3Q", "BasebandPostponementStatusBlob", // iOS pre-12.0
    "yUqD8AXE/c+IggkuYoxrqA", "ChromeIdentifier", // iOS 26.0-
    "YVNo6vlMjhgQ9yGYV8gatw", "PanelSerialNumber", // iOS pre-12.0
    "yZf3GTRMGTuwSV/lD7Cagw", "DeviceSupportsTapToWake", // iOS pre-12.0
    "YzrS+WPEMqyh/FBv/n/jvA", "RearFacingTelephotoCameraCapability", // iOS pre-12.0
    "z+5gEULGC7aEYopBd4ggpA", "BuddyLanguagesAnimationRequiresOptimization", // iOS pre-12.0
    "Z+gc4OJwBMm2YaVtp4usig", "DisplayInactiveBrightnessClass", // iOS 26.0-
    "Z/dqyWS6OZTRy10UcmUAhw", "marketing-name", // iOS pre-12.0
    "Z/TJS0IaLyq10dcSvUTGPg", "DieId", // iOS pre-12.0
    "Z06ZMtQY6G3kKrC7fs/gOA", "marketing-soc-name", // iOS 26.0-
    "Z3gOHeppbL6+rblIe8H5Ag", "BasebandRegionSKURadioTechnology", // iOS pre-12.0
    "z5G/N9jcMdgPm8UegLwbKg", "IsEmulatedDevice", // iOS pre-12.0
    "ZApuwHXWV8RCz0iVzMnqLw", "telephony", // iOS pre-12.0
    "ZeeiT4Cdn8HNANoqroPEAA", "SiriOfflineCapability", // iOS pre-12.0
    "ZEF0po63sTgpVrc9Ce7YNQ", "DMin", // iOS pre-12.0
    "ZeGw3VKUymUAbp4noKsxoQ", "FrontFacingCameraMaxVideoZoomFactor", // iOS pre-12.0
    "ZepchaN1K8XQJaBUMMlV5w", "iAP2Capability", // iOS pre-12.0
    "ZEU7pCEskBhjQ4AOMuALDw", "HEVCDecoder10bitSupported", // iOS pre-12.0
    "ZfUfxSFklLDVCKbgOE7kpg", "OSMigrationCapability", // iOS 26.2
    "ZgIjA7Nwd2jSo13lhDO1Iw", "RegionalBehaviorShutterClick", // iOS pre-12.0
    "ZGraRMW0TsxCvONeeJ5C2w", "HWModelDescriptionForUserVisibility", // iOS 26.0
    "zHeENZu+wbg7PUprwNwBWg", "RegionInfo", // iOS pre-12.0
    "ZiSlYxYSkyaYImU3lrSXWw", "gps", // iOS pre-12.0
    "Zmd7xYUw9EutGXifzpvfsA", "WatchSupportsHighQualityClockFaceGraphics", // iOS pre-12.0
    "zP3kBA1Biwz2d6PTIIbmUQ", "ActivationProtocol", // iOS pre-12.0
    "zPHFWx4ZItDiTXNT2onrWQ", "MobileEquipmentInfoDisplayCSN", // iOS pre-12.0
    "zxMIgVSILN6S5ee6MZhf+Q", "NFCRadio", // iOS pre-12.0
    "ZYqko/XM5zD3XBfN5RmaXA", "MedusaPinnedAppCapability", // iOS pre-12.0
    NULL, NULL
};
