#!/usr/bin/env python3
"""
Script to populate keys_versions.py with iOS version information.

This script reads:
- versions/version-*.txt: Keys introduced in each iOS version (auto-discovered)
- mapping-gestalt.h: All known gestalt keys

And generates keys_versions.py with version annotations.

Example version files:
- versions/version-26.0.txt
- versions/version-26.2.txt
- versions/version-27.0.txt
"""

from pathlib import Path
import re


def extract_hashes_from_mapping(mapping_file: Path) -> set[str]:
    """Extract all obfuscated key hashes from a mapping file."""
    hashes = set()
    
    with mapping_file.open('r') as f:
        for line in f:
            # Match lines like:     "hash", "key_name",
            match = re.match(r'\s*"([^"]+)",\s*"[^"]*",?', line)
            if match:
                hashes.add(match.group(1))
    
    return hashes


def read_version_file(version_file: Path) -> set[str]:
    """Read hashes from a version-specific file (e.g., versions/version-26.0.txt)."""
    hashes = set()
    
    if not version_file.exists():
        print(f"Warning: {version_file} does not exist")
        return hashes
    
    with version_file.open('r') as f:
        for line in f:
            hash_str = line.strip()
            if hash_str:
                hashes.add(hash_str)
    
    return hashes


def generate_keys_versions():
    """Generate keys_versions.py from existing data."""
    
    # File paths
    mapping_gestalt = Path('mapping-gestalt.h')
    output_file = Path('keys_versions.py')
    
    # Extract all hashes from mapping-gestalt.h
    print(f"Reading hashes from {mapping_gestalt}...")
    all_hashes = extract_hashes_from_mapping(mapping_gestalt)
    print(f"Found {len(all_hashes)} total hashes in mapping-gestalt.h\n")
    
    # Auto-discover all version files in versions/ directory
    versions_dir = Path('versions')
    version_files = sorted(versions_dir.glob('version-*.txt')) if versions_dir.exists() else []
    
    if not version_files:
        print("Warning: No version files found in versions/ directory")
        print("Expected format: versions/version-26.0.txt, versions/version-26.2.txt, etc.")
        version_files = []
    
    # Build version mapping
    version_map = {}
    version_stats = {}
    
    # Process version files in order (oldest to newest)
    # Later versions will overwrite earlier ones if a key appears in multiple files
    for version_file in version_files:
        # Extract version from filename (e.g., "version-26.0.txt" -> "26.0")
        version_str = version_file.stem.replace('version-', '')
        
        print(f"Reading hashes from {version_file}...")
        hashes = read_version_file(version_file)
        print(f"Found {len(hashes)} hashes for iOS {version_str}")
        
        # Mark these keys with this version
        for hash_str in hashes:
            version_map[hash_str] = version_str
        
        version_stats[version_str] = len(hashes)
    
    # Mark all remaining keys as pre-26 (or pre-[earliest version])
    if version_files:
        # Get the first version number (already extracted)
        first_file = version_files[0]
        earliest_version = first_file.stem.replace('version-', '')
    else:
        earliest_version = "26"
    pre_version_label = f"pre-{earliest_version}"
    pre_count = 0
    
    for hash_str in all_hashes:
        if hash_str not in version_map:
            version_map[hash_str] = pre_version_label
            pre_count += 1
    
    # Sort for consistent output
    sorted_hashes = sorted(version_map.keys())
    
    # Generate the Python file
    print(f"\nGenerating {output_file}...")
    with output_file.open('w') as f:
        f.write('"""iOS version information for MobileGestalt keys.\n\n')
        f.write('This file is auto-generated by populate_versions.py.\n')
        f.write('Do not edit manually.\n')
        f.write('"""\n\n')
        f.write('# Dictionary mapping obfuscated key hash -> iOS version introduced\n')
        f.write('KEY_IOS_VERSIONS = {\n')
        
        for hash_str in sorted_hashes:
            version = version_map[hash_str]
            f.write(f'    "{hash_str}": "{version}",\n')
        
        f.write('}\n')
    
    # Print statistics
    print(f"\n✓ Generated {output_file}")
    print(f"  - Total keys: {len(version_map)}")
    for version_str, count in sorted(version_stats.items()):
        print(f"  - iOS {version_str}: {count}")
    print(f"  - {pre_version_label}: {pre_count}")


if __name__ == '__main__':
    generate_keys_versions()
