unknown_with_desc = {
    "+xJ6RaQ6PDSsLjib8r5fgg": "IODeviceTree:/product/camera, starts with p, DeviceSupportsCameraCaptureOnTouchDown",
    "0gkWjKWKuS2gqzTaFHKxqw": "IODeviceTree/product/audio, starts with s, DeviceSupportsAdvancedVoiceProcessorChatFlavor",
    "1HWDBfJwBJZ8TDHcPDafmQ": "IODeviceTree:/product, starts with e, DeviceHasEmbeddedSIMOnlyBoard",
    "2aIAScwtFNCz+Y7WesMOCA": "IODeviceTree:/product, starts with m, SecondaryWifiMacAddressData",
    "3Hj0jFscGt094g65Fag7eQ": "Hardware platform, starts with t",
    "8kcKPCGGyCpf66MMl5TVkA": "IODeviceTree:/multi-touch, starts with m, MultiTouchMaxBootTime",
    "dUipfYkyvM80t4IkmMBVgQ": "IODeviceTree:/product, starts with w, DeviceSupportsElton",
    "HhLXszMhK6bb9TP4sqVQWQ": "IODeviceTree:/chosen, starts with e, ExtendedSecurityDomain",
    "jkRyJt34tZOjsO1YhVc0mw": "IODeviceTree:/product/audio, starts with s, AutomaticMicMode",
    "mug/QuG6jZ3CYR9p7OWQaw": "IODeviceTree:/opal, starts with b",
    "oOV1jhJbdV3AddkcCg0AEA": "MetalPerfLevelCapabilityOne4IOS (mismatched)",
    "sad18VQX7AeS+291aKhJlw": "IODeviceTree:/buttons, starts with f, RingerButtonCapability",
    "t56wS9db+T2F2bxBpYSX8Q": "IODeviceTree:/arm-io/disp0, starts with e, DisplayDriverICChipID",
    "tAryHM5IUMkdtvVqqu1tcA": "IODeviceTree:/product, starts with a, AmbientLightSensorSerialNumber",
    "twWCmmM9I0dxwv7Zs9v48Q": "IODeviceTree:/product/audio, starts with a, DeviceSupportseARC",
    "uNNFSosc1xQM/7bwlrqLXA": "IODeviceTree:/arm-io/aop/iop-aop-nub/als, starts with m, DisplayMaxNits",
    "us1armjE6TKGvh2WIrNgEQ": "IODeviceTree:/defaults, starts with a, AlwaysOnDisplayMaxMemory",
    "v1/EHDarbU55OfoXm2EiGA": "IODeviceTree:/product, starts with s, OnDeviceSiriCapability",
    "voS/bmBAz0Y1eNLoN8x9/Q": "IODeviceTree:/product/camera, starts with p, front-depth-camera",
    "vQg8hRTy1PC2j9L+8Jd+vg": "IODeviceTree:/product/audio, starts with s, DeviceSupportsVoiceOverCanUseSiriVoice",
    "vTKPWiAZkQifTv/4/uOnQQ": "IODeviceTree:/product/camera, starts with f, FrontFacingCameraSuperWideCameraCapability",
    "wAbB2fAjUqUc6lNBelfWMA": "IODeviceTree:/product, starts with n, DeviceSupportsPeriodicALSUpdates",
    "xgs6iXf0KFHUJ9d4FKaRYg": "IODeviceTree:/product, starts with s, DeviceSupportsGrey",
    "XyppJjhSQE2982ZYgXlh2g": "IODeviceTree:/stockholm, starts with s, nfc",
    "yeQy+rgNoD7+YIY6mSVOhg": "IODeviceTree:/opal, starts with e",
    "Zg7DduDoSCy6vY6mhy3n2w": "IODeviceTree:/product, starts with i, DeviceSupportsDynamicIsland",
}
