unknown_with_desc = {
    "0Yu30fwSQVPKvHVla17kXw": "UMTSDeviceCapability",
    "1qDdT/85SS7sxriK0wIbbg": "MGIOMFBSupport.c",
    "2oKaRZpltNseA9gTdIKTQQ": "eW5H/Gwg0uqbMqFot70pYg",
    "2tBx5IzZX4CpUVJ79LfsVg": "tribeca",
    "5Y72WwdS5NYHdc00gEZ/DQ": "8DHlxr5ECKhTSL3HmlZQGQ: aqc-a, extlom-mac-address",
    "6WdGcQGw4VLzrgxJo+bcrw": "TF31PAB6aO8KAbPyNKSxKA",
    "8bCjks0zVuOcdivIhytNbQ": "DeviceSupportsLiDAR",
    "8S7ydMJ4DlCUF38/hI/fJA": "PearlCameraCapability",
    "byGRtH44VNik9CzN/QKLCw": "DeviceSupportsNFC",
    "J1QHVh74Nnd6Rqyiq71/yw": "avd AppleARMIODevice > decode-samples-per-second",
    "JWjvsupiqWYtIGwr8yGd8w": "PerfLevelCapabilityTwo4IOS",
    "kT9JwUR2xPCTHTdgvG3UdA": "TorpedoCapability",
    "Lg1EJX11Jb7EbveB6+YgVQ": "Has720PPlaybackCapability",
    "lo3szoQ4sLy7o3+ZD0GcAQ": "primary usage (page)",
    "LTI8wHvEYKy8zR1IXBW1uQ": "displayGamut",
    "LUy+wqFiBmou5hwM5OWbmA": "AppleOceanComputeMCU > Carrier Slot",
    "m7lDS+oP8q0pGg+CO7RvPg": "IODeviceTree:/chosen > 4JalTKSe5a9I+mb00ATvag",
    "Mi/ME+v1wZqkvXFU3xX3KA": "eW5H/Gwg0uqbMqFot70pYg",
    "NDnoY3adyyskgiIQBNtlyQ": "IODeviceTree:/, model-config NED=1",
    "njUcH4bm+JBmvASakDdObg": "IODeviceTree:/arm-io/isp > /4LCTfMhvzuiK6b557ir5Q",
    "OHXV8ldryg9nrOCapcyDCQ": "if DeviceClass = 7",
    "OwiopkU88VSKJX7zgoWPpQ": "DeviceSupportsExternalDriverKit ?",
    "PFnuFyqMMnGUQQnTqS5byg": "IODeviceTree:/product > MlDJggkQz38CLQh3AVv7VQ",
    "qgfS+6l1exvcMW5Tfplv2Q": "AppleOceanComputeMCU > Carrier ID",
    "RNcdWbM8+dO5tx82A+YCcQ": "host UUID",
    "STBQ8gY0pl0CK8VmRcks4w": "IODeviceTree:/product/camera > IvdL59ITgJvhb5ptpLbqRg",
    "TpY9O1U1rtUk/m0BvlO58A": "IODeviceTree:/product > analytics-opt-in",
    "trBC4VS5gVmCv6Wg41Hryw": "IODeviceTree:/avd has ads-present",
    "UoeNJcQ336tc+F5/1r4tqQ": "IODeviceTree:/product > disable-globe-map",
    "VuGdqp8UBpi9vPWHlPluVQ": "array",
    "W/xqvBX9L07XHb0BOtYycQ": "yF2IQrYS4yyREV4ZkbLysw",
    "WAfNjeiwOd/k6+VU6D6SIQ": "5Y72WwdS5NYHdc00gEZ/DQ",
    "wYMBabAO8VguyDDVgCsPdg": ":/arm-io/wlan > AppleBCMWLANCore > ModuleInfo, chip= prefix removed",
    "X9cK3qXzcFCrVpE258P2lQ": "XcmwH6K+Nop/mDqy50Nrqw",
    "XnXl4MhKZx3zRKvA7ZwIYQ": "iPad ? 10 : 20",
    "XYlJKKkj2hztRP1NWWnhlw": "IODeviceTree:/chosen > E3qwwdwgUSy6FV6VC+Uf3A",
    "yF2IQrYS4yyREV4ZkbLysw": "AppleFillmoreDevice, local-mac-address-64",
    "Z06ZMtQY6G3kKrC7fs/gOA": "hSjeLvzobsJCklk4+pzu3g",
    "ZYqko/XM5zD3XBfN5RmaXA": "PiPPinned or IODeviceTree:/product > h9v96tCehBWUil/aJ7UrcA"
}