unknown_with_desc = {
    "0Yu30fwSQVPKvHVla17kXw": "UMTSDeviceCapability (mismatched)",
    "1qDdT/85SS7sxriK0wIbbg": "MGIOMFBSupport.c",
    "2oKaRZpltNseA9gTdIKTQQ": "PerfLevelCapabilityOne4TvOS (mismatched)",
    "2tBx5IzZX4CpUVJ79LfsVg": "tribeca",
    "5Y72WwdS5NYHdc00gEZ/DQ": "8DHlxr5ECKhTSL3HmlZQGQ: aqc-a, extlom-mac-address",
    "8bCjks0zVuOcdivIhytNbQ": "DeviceSupportsLiDAR (mismatched)",
    "8S7ydMJ4DlCUF38/hI/fJA": "PearlCameraCapability (mismatched)",
    "byGRtH44VNik9CzN/QKLCw": "DeviceSupportsNFC (mismatched)",
    "J1QHVh74Nnd6Rqyiq71/yw": "avd AppleARMIODevice > decode-samples-per-second",
    "JWjvsupiqWYtIGwr8yGd8w": "PerfLevelCapabilityTwo4IOS (mismatched)",
    "kT9JwUR2xPCTHTdgvG3UdA": "TorpedoCapability (mismatched)",
    "Lg1EJX11Jb7EbveB6+YgVQ": "Has720PPlaybackCapability (mismatched)",
    "lo3szoQ4sLy7o3+ZD0GcAQ": "AmbientLightSensorCapability (mismatched)",
    "LUy+wqFiBmou5hwM5OWbmA": "AppleOceanComputeMCU > Carrier Slot",
    "m7lDS+oP8q0pGg+CO7RvPg": "IODeviceTree:/chosen > 4JalTKSe5a9I+mb00ATvag",
    "Mi/ME+v1wZqkvXFU3xX3KA": "PerfLevelCapabilityOne4IOS (mismatched)",
    "njUcH4bm+JBmvASakDdObg": "IODeviceTree:/arm-io/isp > /4LCTfMhvzuiK6b557ir5Q",
    "OwiopkU88VSKJX7zgoWPpQ": "DeviceSupportsExternalDriverKit (mismatched)",
    "qgfS+6l1exvcMW5Tfplv2Q": "AppleOceanComputeMCU > Carrier ID",
    "X9cK3qXzcFCrVpE258P2lQ": "HorsemanCapability (mismatched)",
    "yF2IQrYS4yyREV4ZkbLysw": "AppleFillmoreDevice, local-mac-address-64",
    "Z06ZMtQY6G3kKrC7fs/gOA": "MarketingSOCNameString (mismatched)"
}